/**
 * Global type definitions for Next.js 16 typed routes
 * These will be automatically generated by `next typegen` in the future
 * but are manually defined here for now
 */

declare global {
  /**
   * Type helper for page component props with typed params
   */
  type PageProps<T extends string> = {
    params: Promise<ExtractRouteParams<T>>
    searchParams?: Promise<{ [key: string]: string | string[] | undefined }>
  }

  /**
   * Type helper for layout component props with typed params and parallel routes
   */
  type LayoutProps<T extends string> = {
    children: React.ReactNode
    params?: Promise<ExtractRouteParams<T>>
    modal?: React.ReactNode
  }

  /**
   * Helper type to extract route parameters from a route string
   */
  type ExtractRouteParams<T extends string> = T extends `${infer _Start}/[${infer Param}]${infer Rest}`
    ? { [K in Param]: string } & ExtractRouteParams<Rest>
    : {}
}

export {}