# Dependabot configuration for TenantFlow monorepo
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Root package.json and shared dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      # Group all non-major updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "automated"
    assignees:
      - "rhudsontspr"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    
  # Frontend app
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    groups:
      # Group React and related UI updates
      react-ecosystem:
        patterns:
          - "react*"
          - "@tanstack/*"
          - "@radix-ui/*"
          - "@hookform/*"
        update-types:
          - "minor"
          - "patch"
      # Group dev dependencies
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"
    assignees:
      - "rhudsontspr"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"
    
  # Backend app
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    groups:
      # Group NestJS ecosystem updates
      nestjs-ecosystem:
        patterns:
          - "@nestjs/*"
          - "nest-*"
        update-types:
          - "minor"
          - "patch"
      # Group dev dependencies
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    assignees:
      - "rhudsontspr"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"
    # Ignore specific updates that might break
    ignore: []
    # Add any problematic packages here
    # - dependency-name: "example-package"
    #   versions: ["2.x", "3.x"]
    
  # Database package
  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "database"
      - "automated"
    assignees:
      - "rhudsontspr"
    commit-message:
      prefix: "chore(database)"
      include: "scope"
    
  # Shared package
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "shared"
      - "automated"
    assignees:
      - "rhudsontspr"
    commit-message:
      prefix: "chore(shared)"
      include: "scope"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci/cd"
      - "automated"
    assignees:
      - "rhudsontspr"
    commit-message:
      prefix: "ci"
      include: "scope"

