/**
 * `/applications/[id]` — one application's detail and decision surface
 * (APPLY-03, APPLY-04, UI-SPEC §B-5).
 *
 * A ROUTE, NOT A SHEET, AND THAT IS A DECISION WITH THREE REASONS. It is
 * linkable, breadcrumb-able and back-button correct; twenty-six fields are
 * cramped in a sheet at 375px; and approving navigates away regardless, so a
 * sheet would only add a close step. The clinching one is that
 * `submit_rental_application` already writes `/applications/<id>` as the
 * notification's `action_url` (plan 66-04) — a sheet would give that link
 * nowhere to land.
 *
 * A SERVER COMPONENT. No hooks, no database client, no browser API. It awaits
 * `params`, declares the metadata and mounts one client island. Everything
 * interactive — the action bar, the decline dialog, the notes field and the
 * delete confirm — lives inside `<ApplicationDetail />`.
 *
 * `params` IS TYPED EXPLICITLY rather than through the generated `PageProps`
 * helper. That helper is constrained to the route union in
 * `.next/types/routes.d.ts`, which is regenerated by a build; a brand-new route
 * is absent from it until then, so `PageProps<"/applications/[id]">` fails
 * typecheck on a clean checkout. `/tenants/[id]` uses the same explicit shape
 * for its own wrapper.
 *
 * NO ERROR BOUNDARY OF ITS OWN. This page inherits `(owner)/error.tsx`, and the
 * island degrades in place on a failed load (`throwOnError: false` in
 * `query-provider.tsx`). A boundary here would swap the whole route for an error
 * card when a single query blipped.
 */

import type { Metadata } from "next";
import { ApplicationDetail } from "#components/applications/application-detail";

/**
 * Deliberately generic. The applicant's name is resolved client-side under RLS
 * and putting it in the document title would leak it into the browser's history
 * database and into every screenshot of the tab strip — the same reasoning that
 * keeps applicant values out of the conversion query string.
 */
export const metadata: Metadata = {
	title: "Application",
	description: "Review a rental application and record your decision.",
};

export default async function ApplicationDetailPage({
	params,
}: {
	params: Promise<{ id: string }>;
}) {
	const { id } = await params;
	return <ApplicationDetail applicationId={id} />;
}
