# GitGuardian Configuration
# This tells GitGuardian to ignore false positives in test files

version: 2

# Exclude all test files from secret detection
paths-ignore:
  # Test files and directories - THESE ARE NOT REAL SECRETS
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/setup-jest.ts"
  - "**/setup.ts"
  - "**/test-constants.ts"
  - "**/test-users.ts"
  - "**/test-helpers.ts"
  - "**/api-test-helpers.ts"
  
  # Mock and fixture files
  - "**/*mock*.ts"
  - "**/*Mock*.ts"
  - "**/fixtures/**"
  - "**/mocks/**"
  
  # Build outputs
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - ".next/**"
  - "coverage/**"
  
  # Documentation and examples
  - "**/*.md"
  - "**/*.example"
  - "**/*.example.*"
  - ".env.example*"
  - "docs/**"
  
  # Lock files
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"