# Pre-commit hooks for TenantFlow
# Run locally before commits to catch issues early
# Usage: pre-commit install (one time setup)

repos:
  # GitGuardian secret scanning - much faster than CI
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.31.0
    hooks:
      - id: ggshield
        name: GitGuardian scan
        entry: ggshield secret scan pre-commit
        language: python
        stages: [commit]
        types: [text]
        args: ["--timeout", "60"]  # 60s timeout to prevent hanging

  # Basic formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-yaml
        name: Validate YAML files
      - id: check-json
        name: Validate JSON files
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']  # 1MB limit

  # TypeScript/JavaScript formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Format with Prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]
        additional_dependencies:
          - prettier@3.1.0
          - "@prettier/plugin-xml"

  # Optional: Fast ESLint check on staged files only
  - repo: local
    hooks:
      - id: eslint-staged
        name: ESLint (staged files only)
        entry: bash -c 'npm run lint:fix --silent'
        language: system
        types: [javascript, jsx, ts, tsx]
        require_serial: true
        pass_filenames: false