# Add these services to your existing docker-compose.yml
# or run with: docker-compose -f docker-compose.yml -f docker-compose.nocodb-listmonk.yml up -d

version: '3.8'

services:
  # NocoDB - Open Source Airtable Alternative
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      # Connect to your existing PostgreSQL instance
      NC_DB: "pg://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/nocodb"
      NC_AUTH_JWT_SECRET: "${JWT_SECRET:-your-secret-jwt-key-change-this}"
      NC_DISABLE_TELE: "true"  # Disable telemetry
    ports:
      - "8080:8080"
    volumes:
      - nocodb_data:/usr/app/data
    networks:
      - tenantflow_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Listmonk - Open Source Email Marketing
  listmonk:
    image: listmonk/listmonk:latest
    container_name: listmonk
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      LISTMONK_app__address: "0.0.0.0:9000"
      LISTMONK_db__host: "postgres"
      LISTMONK_db__port: "5432"
      LISTMONK_db__user: "postgres"
      LISTMONK_db__password: "${POSTGRES_PASSWORD:-password}"
      LISTMONK_db__database: "listmonk"
      LISTMONK_db__ssl_mode: "disable"
    ports:
      - "9000:9000"
    volumes:
      - listmonk_data:/listmonk/uploads
    networks:
      - tenantflow_network
    command: ["./listmonk", "--install", "--yes", "--idempotent"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:9000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nocodb_data:
    driver: local
  listmonk_data:
    driver: local

networks:
  tenantflow_network:
    external: true
    name: ${NETWORK_NAME:-tenantflow_network}