[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --workspace=@tenantflow/backend --workspace=@tenantflow/shared"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build --filter=@tenantflow/backend"]

[start]
cmd = "cd apps/backend && npm run start:prod"