packages:
  - apps/*
  - packages/*

catalog:
  '@nestjs/common': ^11.1.7
  '@nestjs/core': ^11.1.7
  '@nestjs/platform-express': ^11.1.7
  '@nestjs/swagger': ^11.2.1
  '@nestjs/terminus': ^11.0.0
  '@supabase/ssr': ^0.7.0
  '@supabase/supabase-js': ^2.78.0
  '@types/jest': 30.0.0
  '@types/node': ^24.9.1
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  eslint: ^9.38.0
  jest: 30.2.0
  next: ^15.5.6
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  turbo: ^2.5.8
  typescript: ^5.9.2
  zod: ^4.1.11
