packages:
  - apps/*
  - packages/*

catalog:
  '@nestjs/common': ^11.1.6
  '@nestjs/core': ^11.1.6
  '@nestjs/platform-express': ^11.1.6
  '@nestjs/swagger': ^11.2.0
  '@nestjs/terminus': ^11.0.0
  '@supabase/ssr': ^0.7.0
  '@supabase/supabase-js': ^2.57.4
  '@types/jest': 30.0.0
  '@types/node': ^24.5.2
  '@types/react': 19.1.13
  '@types/react-dom': 19.1.9
  eslint: ^9.36.0
  jest: 30.2.0
  next: ^15.5.3
  posthog-js: ^1.268.0
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  turbo: ^2.5.6
  typescript: ^5.9.2
  zod: ^4.1.11
