packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # Core dependencies
  typescript: 5.9.2

  # React ecosystem
  react: ^19.1.1
  react-dom: ^19.1.1
  '@types/react': ^19.1.13
  '@types/react-dom': 19.1.9

  # Next.js
  next: ^15.5.0

  # Node types
  '@types/node': ^24.5.2

  # NestJS ecosystem
  '@nestjs/common': ^11.1.6
  '@nestjs/core': ^11.1.6
  '@nestjs/platform-fastify': ^11.1.6
  '@nestjs/swagger': ^8.1.4
  '@nestjs/terminus': 11.0.0

  # Supabase
  '@supabase/supabase-js': ^2.57.4
  '@supabase/ssr': ^0.7.0

  # Testing
  jest: ^30.5.9
  '@types/jest': ^30.5.9

  # Linting & Formatting
  eslint: ^9.36.0
  prettier: ^3.5.3

  # Build tools
  turbo: 2.5.6
  vite: ^6.0.14

  # Zod
  zod: ^4.1.9
