catalog:
  # Core dependencies
  '@nestjs/common': ^11.1.6

  # React ecosystem
  '@nestjs/core': ^11.1.6
  '@nestjs/platform-fastify': ^11.1.6
  '@nestjs/swagger': ^11.2.0
  '@nestjs/terminus': 11.0.0

  # Next.js
  '@supabase/ssr': ^0.7.0

  # Node types
  '@supabase/supabase-js': ^2.57.4

  # NestJS ecosystem
  '@types/jest': ^30.0.0
  '@types/node': ^24.5.2
  '@types/react': ^19.1.13
  '@types/react-dom': 19.1.9
  eslint: ^9.36.0

  # Supabase
  jest: ^30.1.3
  next: ^15.5.3

  # Testing
  prettier: ^3.6.2
  react: ^19.1.1

  # Linting & Formatting
  react-dom: ^19.1.1
  turbo: 2.5.6

  # Build tools
  typescript: 5.9.2

  # Zod
  zod: ^4.1.9

packages:
  - 'apps/*'
  - 'packages/*'
