packages:
  - apps/*
  - packages/*

catalog:
  '@nestjs/common': ^11.1.7
  '@nestjs/core': ^11.1.7
  '@nestjs/platform-express': ^11.1.7
  '@nestjs/swagger': ^11.2.1
  '@nestjs/terminus': ^11.0.0
  '@supabase/ssr': ^0.8.0
  '@supabase/supabase-js': 2.87.0
  '@types/jest': 30.0.0
  '@types/node': ^24.10.1
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  eslint: 9.39.1
  jest: 30.2.0
  next: ^16.0.0
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  turbo: ^2.6.1
  typescript: ^5.9.2
  zod: ^4.1.13
