/* eslint-disable color-tokens/no-hex-colors -- PDF document uses inline CSS for StirlingPDF, not Tailwind */
import type { TemplatePreviewOptions } from './template-types'

/**
 * Escape HTML special characters to prevent XSS in generated PDF.
 * This is a standalone helper (not imported from Edge Function _shared/).
 */
function escapeHtml(text: string): string {
	return text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#39;')
}

/**
 * Convert a camelCase or snake_case key to a title-cased label.
 * e.g. "moveInDate" -> "Move In Date", "property_name" -> "Property Name"
 */
function toTitleCase(key: string): string {
	return key
		.replace(/([a-z])([A-Z])/g, '$1 $2')
		.replace(/_/g, ' ')
		.replace(/\b\w/g, (c) => c.toUpperCase())
}

function renderFieldRow(label: string, value: string): string {
	return `<div class="field-row"><span class="field-label">${escapeHtml(label)}</span><span class="field-value">${escapeHtml(value)}</span></div>`
}

function renderDataSection(
	data: Record<string, unknown>
): string {
	const sections: string[] = []

	for (const [key, value] of Object.entries(data)) {
		if (key === 'dynamicFields') continue

		if (
			value !== null &&
			typeof value === 'object' &&
			!Array.isArray(value)
		) {
			const obj = value as Record<string, unknown>
			sections.push(
				`<h2 class="section-title">${escapeHtml(toTitleCase(key))}</h2>`
			)
			for (const [subKey, subValue] of Object.entries(obj)) {
				sections.push(
					renderFieldRow(toTitleCase(subKey), String(subValue ?? ''))
				)
			}
		} else {
			sections.push(
				renderFieldRow(toTitleCase(key), String(value ?? ''))
			)
		}
	}

	return sections.join('\n')
}

/**
 * Convert TemplatePreviewOptions into a full HTML document string
 * suitable for the generate-pdf Edge Function's { html } mode.
 *
 * All user-provided text is HTML-escaped to prevent XSS.
 * Styles are fully inline (no external stylesheets -- StirlingPDF renders in isolation).
 */
export function buildTemplateHtml(
	options: TemplatePreviewOptions
): string {
	const { templateTitle, state, branding, customFields, clauses, data } =
		options

	const stateInfo = state
		? ` &middot; ${escapeHtml(state)}`
		: ''

	const customFieldsHtml =
		customFields.length > 0
			? `<h2 class="section-title">Additional Information</h2>\n${customFields.map((f) => renderFieldRow(f.label, f.value)).join('\n')}`
			: ''

	const clausesHtml =
		clauses.length > 0
			? `<h2 class="section-title">Terms &amp; Conditions</h2>\n<ol class="clause-list">${clauses.map((c) => `<li class="clause-item">${escapeHtml(c.text)}</li>`).join('\n')}</ol>`
			: ''

	const today = new Date().toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	})

	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${escapeHtml(templateTitle)}</title>
<style>
body { font-family: Arial, sans-serif; margin: 32px; color: #222; }
h1 { font-size: 22px; color: ${escapeHtml(branding.primaryColor)}; margin-bottom: 4px; }
.company { font-size: 14px; color: #666; margin-bottom: 16px; }
.section-title { font-size: 16px; font-weight: 600; margin-top: 20px; margin-bottom: 8px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
.field-row { display: flex; padding: 4px 0; font-size: 13px; }
.field-label { font-weight: 500; min-width: 180px; color: #444; }
.field-value { flex: 1; }
.clause-list { list-style-type: decimal; padding-left: 20px; }
.clause-item { margin-bottom: 6px; font-size: 13px; }
.footer { margin-top: 32px; border-top: 1px solid #ddd; padding-top: 12px; font-size: 11px; color: #888; }
</style>
</head>
<body>
<h1>${escapeHtml(templateTitle)}</h1>
<p class="company">${escapeHtml(branding.companyName)}${stateInfo}</p>
${renderDataSection(data)}
${customFieldsHtml}
${clausesHtml}
<div class="footer">Generated by ${escapeHtml(branding.companyName)} via TenantFlow &middot; ${today}</div>
</body>
</html>`
}
