/**
 * Validation limits used across forms and Zod schemas.
 *
 * The previous BILLING_PLANS export here drifted into stale parallel
 * pricing data ($19/$49/$99 with wrong limits). It was deleted in v2.7
 * Phase 67 cycle-6. The single source of truth for pricing/plans is now
 * `PRICING_PLANS` in `src/config/pricing.ts` — call `getAllPricingPlans()`
 * or `getPricingPlan(planId)` instead of importing anything from here.
 */

export const VALIDATION_LIMITS = {
	PROPERTY_NAME_MAX_LENGTH: 100,
	PROPERTY_DESCRIPTION_MAX_LENGTH: 2000,
	UNIT_NUMBER_MAX_LENGTH: 20,
	UNIT_BEDROOM_BATHROOM_MAX: 50,
	RENT_MAXIMUM_VALUE: 1000000,
	SQUARE_FOOTAGE_MAXIMUM: 1000000,
	SALE_PRICE_MAXIMUM: 100000000,
	PROPERTY_UNIT_MAX_BEDROOMS: 50,
	PROPERTY_UNIT_MAX_BATHROOMS: 50,
	UNIT_MAX_BEDROOMS: 20,
	UNIT_MAX_BATHROOMS: 20,
	UNIT_MAX_SQUARE_FEET: 50000,
	UNIT_RENT_MAXIMUM: 100000,
	API_QUERY_MAX_LIMIT: 100,
	API_QUERY_DEFAULT_LIMIT: 10,
	API_QUERY_DEFAULT_PAGE: 1,
	PASSWORD_MIN_LENGTH: 8,
	CONTACT_FORM_NAME_MAX_LENGTH: 100,
	CONTACT_FORM_EMAIL_MAX_LENGTH: 254,
	CONTACT_FORM_SUBJECT_MAX_LENGTH: 200,
	CONTACT_FORM_MESSAGE_MIN_LENGTH: 10,
	CONTACT_FORM_MESSAGE_MAX_LENGTH: 5000,
	CONTACT_FORM_PHONE_MAX_LENGTH: 20,
	TITLE_MAX_LENGTH: 200,
	DESCRIPTION_MAX_LENGTH: 2000,
};
