"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERROR_REPORTING_LEVELS = exports.ERROR_METRICS = exports.COMMON_ERROR_MESSAGES = exports.ERROR_ACTIONS = exports.ERROR_CONTEXT_TYPES = exports.ERROR_TYPES = exports.ERROR_CATEGORIES = exports.ERROR_SEVERITY = exports.API_ERROR_CODES = void 0;
exports.API_ERROR_CODES = {
    AUTH_INVALID_CREDENTIALS: 'AUTH-001',
    AUTH_EMAIL_NOT_VERIFIED: 'AUTH-002',
    AUTH_ACCOUNT_LOCKED: 'AUTH-003',
    AUTH_PASSWORD_WEAK: 'AUTH-004',
    AUTH_EMAIL_EXISTS: 'AUTH-005',
    AUTH_INVALID_TOKEN: 'AUTH-006',
    AUTH_TOKEN_EXPIRED: 'AUTH-007',
    AUTH_RATE_LIMITED: 'AUTH-008',
    AUTH_NETWORK_ERROR: 'AUTH-009',
    AUTH_VALIDATION_ERROR: 'AUTH-010',
    AUTH_UNKNOWN_ERROR: 'AUTH-999',
    VALIDATION_INVALID_EMAIL: 'VALIDATION-001',
    VALIDATION_INVALID_PHONE: 'VALIDATION-002',
    VALIDATION_INVALID_DATE: 'VALIDATION-003',
    VALIDATION_INVALID_AMOUNT: 'VALIDATION-004',
    VALIDATION_INVALID_FORMAT: 'VALIDATION-005',
    VALIDATION_REQUIRED_FIELD: 'VALIDATION-006',
    VALIDATION_MIN_LENGTH: 'VALIDATION-007',
    VALIDATION_MAX_LENGTH: 'VALIDATION-008',
    VALIDATION_MIN_VALUE: 'VALIDATION-009',
    VALIDATION_MAX_VALUE: 'VALIDATION-010',
    VALIDATION_INVALID_ENUM: 'VALIDATION-011',
    RESOURCE_NOT_FOUND: 'RESOURCE-001',
    RESOURCE_CONFLICT: 'RESOURCE-002',
    RESOURCE_UNAUTHORIZED: 'RESOURCE-003',
    RESOURCE_FORBIDDEN: 'RESOURCE-004',
    RESOURCE_RATE_LIMIT: 'RESOURCE-005',
    RESOURCE_INTERNAL_ERROR: 'RESOURCE-006',
    RESOURCE_EXTERNAL_SERVICE_ERROR: 'RESOURCE-007',
    PAYMENT_DECLINED: 'PAYMENT-001',
    PAYMENT_INSUFFICIENT_FUNDS: 'PAYMENT-002',
    PAYMENT_CARD_EXPIRED: 'PAYMENT-003',
    PAYMENT_INVALID_CARD: 'PAYMENT-004',
    PAYMENT_PROCESSING_FAILED: 'PAYMENT-005',
    PAYMENT_DUPLICATE_TRANSACTION: 'PAYMENT-006',
    PAYMENT_EXCEEDS_LIMIT: 'PAYMENT-007',
    DB_CONNECTION_FAILED: 'DB-001',
    DB_QUERY_TIMEOUT: 'DB-002',
    DB_CONSTRAINT_VIOLATION: 'DB-003',
    DB_UNIQUE_CONSTRAINT: 'DB-004',
    DB_FOREIGN_KEY_VIOLATION: 'DB-005',
    DB_INVALID_INPUT: 'DB-006',
    DB_TRANSACTION_FAILED: 'DB-007',
    STRIPE_CARD_ERROR: 'STRIPE-001',
    STRIPE_RATE_LIMIT_ERROR: 'STRIPE-002',
    STRIPE_INVALID_REQUEST_ERROR: 'STRIPE-003',
    STRIPE_AUTHENTICATION_ERROR: 'STRIPE-004',
    STRIPE_API_CONNECTION_ERROR: 'STRIPE-005',
    STRIPE_SIGNATURE_VERIFICATION_ERROR: 'STRIPE-006',
    FILE_SIZE_EXCEEDED: 'FILE-001',
    FILE_TYPE_INVALID: 'FILE-002',
    FILE_UPLOAD_FAILED: 'FILE-003',
    FILE_PROCESSING_ERROR: 'FILE-004',
    FILE_STORAGE_QUOTA_EXCEEDED: 'FILE-005',
    BUSINESS_INVALID_STATE: 'BUSINESS-001',
    BUSINESS_INSUFFICIENT_PERMISSIONS: 'BUSINESS-002',
    BUSINESS_INVALID_OPERATION: 'BUSINESS-003',
    BUSINESS_DEPENDENCY_MISSING: 'BUSINESS-004',
    BUSINESS_QUOTA_EXCEEDED: 'BUSINESS-005'
};
exports.ERROR_SEVERITY = {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL'
};
exports.ERROR_CATEGORIES = {
    AUTHENTICATION: 'AUTHENTICATION',
    VALIDATION: 'VALIDATION',
    NETWORK: 'NETWORK',
    DATABASE: 'DATABASE',
    PAYMENT: 'PAYMENT',
    BUSINESS_LOGIC: 'BUSINESS_LOGIC',
    FILE_OPERATIONS: 'FILE_OPERATIONS',
    EXTERNAL_SERVICES: 'EXTERNAL_SERVICES',
    UNKNOWN: 'UNKNOWN'
};
exports.ERROR_TYPES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    CONFLICT_ERROR: 'CONFLICT_ERROR',
    RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR'
};
exports.ERROR_CONTEXT_TYPES = {
    REQUEST: 'REQUEST',
    DATABASE: 'DATABASE',
    AUTHENTICATION: 'AUTHENTICATION',
    VALIDATION: 'VALIDATION',
    PAYMENT: 'PAYMENT',
    FILE_UPLOAD: 'FILE_UPLOAD',
    BUSINESS_LOGIC: 'BUSINESS_LOGIC'
};
exports.ERROR_ACTIONS = {
    RETRY: 'RETRY',
    CONTACT_SUPPORT: 'CONTACT_SUPPORT',
    CHECK_INPUT: 'CHECK_INPUT',
    VERIFY_AUTH: 'VERIFY_AUTH',
    CHECK_CONNECTION: 'CHECK_CONNECTION',
    UPGRADE_PLAN: 'UPGRADE_PLAN',
    CONTACT_ADMIN: 'CONTACT_ADMIN'
};
exports.COMMON_ERROR_MESSAGES = {
    NETWORK_DISCONNECTED: 'Unable to connect to the server. Please check your internet connection.',
    RATE_LIMIT_EXCEEDED: 'Too many requests. Please try again later.',
    UNAUTHORIZED_ACCESS: 'You do not have permission to access this resource.',
    RESOURCE_NOT_FOUND: 'The requested resource could not be found.',
    VALIDATION_FAILED: 'The provided data is invalid. Please check the highlighted fields.',
    PAYMENT_FAILED: 'Payment processing failed. Please verify your payment information.',
    INTERNAL_SERVER_ERROR: 'An unexpected error occurred. Our team has been notified.',
    FILE_UPLOAD_FAILED: 'File upload failed. Please try again or contact support.',
    INVALID_CREDENTIALS: 'Invalid email or password. Please try again.'
};
exports.ERROR_METRICS = {
    COUNT: 'COUNT',
    FREQUENCY: 'FREQUENCY',
    IMPACT: 'IMPACT',
    RESOLUTION_TIME: 'RESOLUTION_TIME',
    USER_IMPACT: 'USER_IMPACT'
};
exports.ERROR_REPORTING_LEVELS = {
    DEBUG: 'DEBUG',
    INFO: 'INFO',
    WARNING: 'WARNING',
    ERROR: 'ERROR',
    CRITICAL: 'CRITICAL'
};
//# sourceMappingURL=error-codes.js.map