/**
 * CENTRALIZED ERROR CODES - Single source of truth for all error codes
 *
 * Consolidates all duplicate error codes from across the codebase into one location
 * following TypeScript 5.9.2 performance patterns with const assertions.
 */

export const API_ERROR_CODES = {
	// Authentication errors (AUTH-xxx)
	AUTH_INVALID_CREDENTIALS: 'AUTH-001',
	AUTH_EMAIL_NOT_VERIFIED: 'AUTH-002',
	AUTH_ACCOUNT_LOCKED: 'AUTH-003',
	AUTH_PASSWORD_WEAK: 'AUTH-004',
	AUTH_EMAIL_EXISTS: 'AUTH-005',
	AUTH_INVALID_TOKEN: 'AUTH-006',
	AUTH_TOKEN_EXPIRED: 'AUTH-007',
	AUTH_RATE_LIMITED: 'AUTH-008',
	AUTH_NETWORK_ERROR: 'AUTH-009',
	AUTH_VALIDATION_ERROR: 'AUTH-010',
	AUTH_UNKNOWN_ERROR: 'AUTH-999',

	// Validation errors (VALIDATION-xxx)
	VALIDATION_INVALID_EMAIL: 'VALIDATION-001',
	VALIDATION_INVALID_PHONE: 'VALIDATION-002',
	VALIDATION_INVALID_DATE: 'VALIDATION-003',
	VALIDATION_INVALID_AMOUNT: 'VALIDATION-004',
	VALIDATION_INVALID_FORMAT: 'VALIDATION-005',
	VALIDATION_REQUIRED_FIELD: 'VALIDATION-006',
	VALIDATION_MIN_LENGTH: 'VALIDATION-007',
	VALIDATION_MAX_LENGTH: 'VALIDATION-008',
	VALIDATION_MIN_VALUE: 'VALIDATION-009',
	VALIDATION_MAX_VALUE: 'VALIDATION-010',
	VALIDATION_INVALID_ENUM: 'VALIDATION-011',

	// Resource errors (RESOURCE-xxx)
	RESOURCE_NOT_FOUND: 'RESOURCE-001',
	RESOURCE_CONFLICT: 'RESOURCE-002',
	RESOURCE_UNAUTHORIZED: 'RESOURCE-003',
	RESOURCE_FORBIDDEN: 'RESOURCE-004',
	RESOURCE_RATE_LIMIT: 'RESOURCE-005',
	RESOURCE_INTERNAL_ERROR: 'RESOURCE-006',
	RESOURCE_EXTERNAL_SERVICE_ERROR: 'RESOURCE-007',

	// Payment errors (PAYMENT-xxx)
	PAYMENT_DECLINED: 'PAYMENT-001',
	PAYMENT_INSUFFICIENT_FUNDS: 'PAYMENT-002',
	PAYMENT_CARD_EXPIRED: 'PAYMENT-003',
	PAYMENT_INVALID_CARD: 'PAYMENT-004',
	PAYMENT_PROCESSING_FAILED: 'PAYMENT-005',
	PAYMENT_DUPLICATE_TRANSACTION: 'PAYMENT-006',
	PAYMENT_EXCEEDS_LIMIT: 'PAYMENT-007',

	// Database errors (DB-xxx)
	DB_CONNECTION_FAILED: 'DB-001',
	DB_QUERY_TIMEOUT: 'DB-002',
	DB_CONSTRAINT_VIOLATION: 'DB-003',
	DB_UNIQUE_CONSTRAINT: 'DB-004',
	DB_FOREIGN_KEY_VIOLATION: 'DB-005',
	DB_INVALID_INPUT: 'DB-006',
	DB_TRANSACTION_FAILED: 'DB-007',

	// Stripe errors (STRIPE-xxx)
	STRIPE_CARD_ERROR: 'STRIPE-001',
	STRIPE_RATE_LIMIT_ERROR: 'STRIPE-002',
	STRIPE_INVALID_REQUEST_ERROR: 'STRIPE-003',
	STRIPE_AUTHENTICATION_ERROR: 'STRIPE-004',
	STRIPE_API_CONNECTION_ERROR: 'STRIPE-005',
	STRIPE_SIGNATURE_VERIFICATION_ERROR: 'STRIPE-006',

	// File upload errors (FILE-xxx)
	FILE_SIZE_EXCEEDED: 'FILE-001',
	FILE_TYPE_INVALID: 'FILE-002',
	FILE_UPLOAD_FAILED: 'FILE-003',
	FILE_PROCESSING_ERROR: 'FILE-004',
	FILE_STORAGE_QUOTA_EXCEEDED: 'FILE-005',

	// Business logic errors (BUSINESS-xxx)
	BUSINESS_INVALID_STATE: 'BUSINESS-001',
	BUSINESS_INSUFFICIENT_PERMISSIONS: 'BUSINESS-002',
	BUSINESS_INVALID_OPERATION: 'BUSINESS-003',
	BUSINESS_DEPENDENCY_MISSING: 'BUSINESS-004',
	BUSINESS_QUOTA_EXCEEDED: 'BUSINESS-005'
} as const

export type ApiErrorCode =
	(typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES]

/**
 * ERROR SEVERITY CLASSIFICATION
 * Performance-optimized const object for error severity levels
 */
export const ERROR_SEVERITY = {
	LOW: 'LOW',
	MEDIUM: 'MEDIUM',
	HIGH: 'HIGH',
	CRITICAL: 'CRITICAL'
} as const

export type ErrorSeverity = (typeof ERROR_SEVERITY)[keyof typeof ERROR_SEVERITY]

/**
 * ERROR CATEGORIES
 * Group errors by functional area for better organization
 */
export const ERROR_CATEGORIES = {
	AUTHENTICATION: 'AUTHENTICATION',
	VALIDATION: 'VALIDATION',
	NETWORK: 'NETWORK',
	DATABASE: 'DATABASE',
	PAYMENT: 'PAYMENT',
	BUSINESS_LOGIC: 'BUSINESS_LOGIC',
	FILE_OPERATIONS: 'FILE_OPERATIONS',
	EXTERNAL_SERVICES: 'EXTERNAL_SERVICES',
	UNKNOWN: 'UNKNOWN'
} as const

export type ErrorCategory =
	(typeof ERROR_CATEGORIES)[keyof typeof ERROR_CATEGORIES]

/**
 * ERROR TYPES - Consolidated from multiple duplicate type definitions
 */
export const ERROR_TYPES = {
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	NETWORK_ERROR: 'NETWORK_ERROR',
	AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
	AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
	NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
	CONFLICT_ERROR: 'CONFLICT_ERROR',
	RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
	EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
	UNKNOWN_ERROR: 'UNKNOWN_ERROR'
} as const

export type ErrorType = (typeof ERROR_TYPES)[keyof typeof ERROR_TYPES]

/**
 * ERROR CONTEXT TYPES - For detailed error tracking
 */
export const ERROR_CONTEXT_TYPES = {
	REQUEST: 'REQUEST',
	DATABASE: 'DATABASE',
	AUTHENTICATION: 'AUTHENTICATION',
	VALIDATION: 'VALIDATION',
	PAYMENT: 'PAYMENT',
	FILE_UPLOAD: 'FILE_UPLOAD',
	BUSINESS_LOGIC: 'BUSINESS_LOGIC'
} as const

export type ErrorContextType =
	(typeof ERROR_CONTEXT_TYPES)[keyof typeof ERROR_CONTEXT_TYPES]

/**
 * ERROR ACTION TYPES - Recommended actions for different error types
 */
export const ERROR_ACTIONS = {
	RETRY: 'RETRY',
	CONTACT_SUPPORT: 'CONTACT_SUPPORT',
	CHECK_INPUT: 'CHECK_INPUT',
	VERIFY_AUTH: 'VERIFY_AUTH',
	CHECK_CONNECTION: 'CHECK_CONNECTION',
	UPGRADE_PLAN: 'UPGRADE_PLAN',
	CONTACT_ADMIN: 'CONTACT_ADMIN'
} as const

export type ErrorAction = (typeof ERROR_ACTIONS)[keyof typeof ERROR_ACTIONS]

/**
 * COMMON ERROR MESSAGES - Standardized user-facing messages
 */
export const COMMON_ERROR_MESSAGES = {
	NETWORK_DISCONNECTED:
		'Unable to connect to the server. Please check your internet connection.',
	RATE_LIMIT_EXCEEDED: 'Too many requests. Please try again later.',
	UNAUTHORIZED_ACCESS: 'You do not have permission to access this resource.',
	RESOURCE_NOT_FOUND: 'The requested resource could not be found.',
	VALIDATION_FAILED:
		'The provided data is invalid. Please check the highlighted fields.',
	PAYMENT_FAILED:
		'Payment processing failed. Please verify your payment information.',
	INTERNAL_SERVER_ERROR:
		'An unexpected error occurred. Our team has been notified.',
	FILE_UPLOAD_FAILED:
		'File upload failed. Please try again or contact support.',
	INVALID_CREDENTIALS: 'Invalid email or password. Please try again.'
} as const

/**
 * ERROR METRICS - Track error patterns and frequencies
 */
export const ERROR_METRICS = {
	COUNT: 'COUNT',
	FREQUENCY: 'FREQUENCY',
	IMPACT: 'IMPACT',
	RESOLUTION_TIME: 'RESOLUTION_TIME',
	USER_IMPACT: 'USER_IMPACT'
} as const

export type ErrorMetric = (typeof ERROR_METRICS)[keyof typeof ERROR_METRICS]

/**
 * ERROR REPORTING LEVELS - For logging and monitoring
 */
export const ERROR_REPORTING_LEVELS = {
	DEBUG: 'DEBUG',
	INFO: 'INFO',
	WARNING: 'WARNING',
	ERROR: 'ERROR',
	CRITICAL: 'CRITICAL'
} as const

export type ErrorReportingLevel =
	(typeof ERROR_REPORTING_LEVELS)[keyof typeof ERROR_REPORTING_LEVELS]

/**
 * HTTP STATUS CODES - Standardized HTTP status codes
 */
export const HTTP_STATUS_CODES = {
	// Client errors (4xx)
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	PAYMENT_REQUIRED: 402,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	METHOD_NOT_ALLOWED: 405,
	CONFLICT: 409,
	UNPROCESSABLE_ENTITY: 422,
	TOO_MANY_REQUESTS: 429,

	// Server errors (5xx)
	INTERNAL_SERVER_ERROR: 500,
	NOT_IMPLEMENTED: 501,
	BAD_GATEWAY: 502,
	SERVICE_UNAVAILABLE: 503,
	GATEWAY_TIMEOUT: 504
} as const

export type HttpStatusCode =
	(typeof HTTP_STATUS_CODES)[keyof typeof HTTP_STATUS_CODES]

/**
 * BUSINESS ERROR CODES - Domain-specific error codes
 */
export const BUSINESS_ERROR_CODES = {
	// Property errors
	PROPERTY_NOT_FOUND: 'PROPERTY_NOT_FOUND',
	UNIT_NOT_AVAILABLE: 'UNIT_NOT_AVAILABLE',

	// Tenant errors
	TENANT_ALREADY_EXISTS: 'TENANT_ALREADY_EXISTS',

	// Lease errors
	LEASE_OVERLAP: 'LEASE_OVERLAP',
	INVALID_LEASE_DATES: 'INVALID_LEASE_DATES',

	// Maintenance errors
	MAINTENANCE_REQUEST_CLOSED: 'MAINTENANCE_REQUEST_CLOSED',

	// Billing errors
	BILLING_ERROR: 'BILLING_ERROR',
	SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',

	// File upload errors
	INVALID_CSV_FORMAT: 'INVALID_CSV_FORMAT',
	FILE_TOO_LARGE: 'FILE_TOO_LARGE',
	INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
	NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',

	// CSV-specific validation errors
	CSV_MISSING_REQUIRED_COLUMNS: 'CSV_MISSING_REQUIRED_COLUMNS',
	CSV_INVALID_DATA: 'CSV_INVALID_DATA',
	CSV_DUPLICATE_ENTRIES: 'CSV_DUPLICATE_ENTRIES',

	// Permission errors
	INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

	// Network errors
	NETWORK_ERROR: 'NETWORK_ERROR',
	CORS_ERROR: 'CORS_ERROR'
} as const

export type BusinessErrorCode =
	(typeof BUSINESS_ERROR_CODES)[keyof typeof BUSINESS_ERROR_CODES]

/**
 * Standard error messages for common scenarios
 */
export const API_ERROR_MESSAGES = {
	VALIDATION_FAILED: 'Validation failed',
	UNAUTHORIZED_ACCESS: 'Unauthorized access',
	RESOURCE_NOT_FOUND: 'Resource not found',
	INTERNAL_ERROR: 'Internal server error',
	BAD_REQUEST: 'Bad request',
	FORBIDDEN: 'Access forbidden',
	CONFLICT: 'Resource conflict',
	TOO_MANY_REQUESTS: 'Too many requests',
	SERVICE_UNAVAILABLE: 'Service temporarily unavailable'
} as const
