"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MS_PER_SECOND = exports.MS_PER_MINUTE = exports.MS_PER_HOUR = exports.MS_PER_DAY = exports.FIFTEEN_MINUTES = exports.THIRTY_MINUTES = exports.SIXTY_MINUTES = exports.SIX_HOURS = exports.TWELVE_HOURS = exports.TWENTY_FOUR_HOURS = exports.ONE_DAY = exports.SEVEN_DAYS = exports.THIRTY_DAYS = exports.ONE_DAY_IN_MS = exports.SEVEN_DAYS_IN_MS = exports.THIRTY_DAYS_IN_MS = exports.WEEK = exports.DAY = exports.HOUR = exports.MINUTE = exports.SECOND = exports.MILLISECOND = exports.TIME_CONSTANTS = void 0;
exports.TIME_CONSTANTS = {
    MILLISECOND: 1,
    SECOND: 1000,
    MINUTE: 60000,
    HOUR: 3600000,
    DAY: 86400000,
    WEEK: 604800000,
    THIRTY_DAYS_IN_MS: 2592000000,
    SEVEN_DAYS_IN_MS: 604800000,
    ONE_DAY_IN_MS: 86400000,
    THIRTY_DAYS: 30,
    SEVEN_DAYS: 7,
    ONE_DAY: 1,
    TWENTY_FOUR_HOURS: 24,
    TWELVE_HOURS: 12,
    SIX_HOURS: 6,
    SIXTY_MINUTES: 60,
    THIRTY_MINUTES: 30,
    FIFTEEN_MINUTES: 15,
    MS_PER_DAY: 86400000,
    MS_PER_HOUR: 3600000,
    MS_PER_MINUTE: 60000,
    MS_PER_SECOND: 1000
};
exports.MILLISECOND = exports.TIME_CONSTANTS.MILLISECOND, exports.SECOND = exports.TIME_CONSTANTS.SECOND, exports.MINUTE = exports.TIME_CONSTANTS.MINUTE, exports.HOUR = exports.TIME_CONSTANTS.HOUR, exports.DAY = exports.TIME_CONSTANTS.DAY, exports.WEEK = exports.TIME_CONSTANTS.WEEK, exports.THIRTY_DAYS_IN_MS = exports.TIME_CONSTANTS.THIRTY_DAYS_IN_MS, exports.SEVEN_DAYS_IN_MS = exports.TIME_CONSTANTS.SEVEN_DAYS_IN_MS, exports.ONE_DAY_IN_MS = exports.TIME_CONSTANTS.ONE_DAY_IN_MS, exports.THIRTY_DAYS = exports.TIME_CONSTANTS.THIRTY_DAYS, exports.SEVEN_DAYS = exports.TIME_CONSTANTS.SEVEN_DAYS, exports.ONE_DAY = exports.TIME_CONSTANTS.ONE_DAY, exports.TWENTY_FOUR_HOURS = exports.TIME_CONSTANTS.TWENTY_FOUR_HOURS, exports.TWELVE_HOURS = exports.TIME_CONSTANTS.TWELVE_HOURS, exports.SIX_HOURS = exports.TIME_CONSTANTS.SIX_HOURS, exports.SIXTY_MINUTES = exports.TIME_CONSTANTS.SIXTY_MINUTES, exports.THIRTY_MINUTES = exports.TIME_CONSTANTS.THIRTY_MINUTES, exports.FIFTEEN_MINUTES = exports.TIME_CONSTANTS.FIFTEEN_MINUTES, exports.MS_PER_DAY = exports.TIME_CONSTANTS.MS_PER_DAY, exports.MS_PER_HOUR = exports.TIME_CONSTANTS.MS_PER_HOUR, exports.MS_PER_MINUTE = exports.TIME_CONSTANTS.MS_PER_MINUTE, exports.MS_PER_SECOND = exports.TIME_CONSTANTS.MS_PER_SECOND;
//# sourceMappingURL=time.js.map