[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = ["cd ../.. && npm ci"]

[phases.build] 
cmds = ["cd ../.. && npm run build --filter=@tenantflow/backend"]

[start]
cmd = "npm run start:prod"