-- net schema (pg_net extension)
-- HTTP functions for outbound requests from database
-- Functions: http_get, http_post, http_delete, http_collect_response

                                                                                                          pg_get_functiondef                                                                                                          
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION net._await_response(request_id bigint)                                                                                                                                                                   +
  RETURNS boolean                                                                                                                                                                                                                    +
  LANGUAGE plpgsql                                                                                                                                                                                                                   +
 AS $function$                                                                                                                                                                                                                       +
 declare                                                                                                                                                                                                                             +
     rec net._http_response;                                                                                                                                                                                                         +
 begin                                                                                                                                                                                                                               +
     while rec is null loop                                                                                                                                                                                                          +
         select *                                                                                                                                                                                                                    +
         into rec                                                                                                                                                                                                                    +
         from net._http_response                                                                                                                                                                                                     +
         where id = request_id;                                                                                                                                                                                                      +
                                                                                                                                                                                                                                     +
         if rec is null then                                                                                                                                                                                                         +
             -- Wait 50 ms before checking again                                                                                                                                                                                     +
             perform pg_sleep(0.05);                                                                                                                                                                                                 +
         end if;                                                                                                                                                                                                                     +
     end loop;                                                                                                                                                                                                                       +
                                                                                                                                                                                                                                     +
     return true;                                                                                                                                                                                                                    +
 end;                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                          +
 
 CREATE OR REPLACE FUNCTION net._encode_url_with_params_array(url text, params_array text[])                                                                                                                                         +
  RETURNS text                                                                                                                                                                                                                       +
  LANGUAGE c                                                                                                                                                                                                                         +
  IMMUTABLE                                                                                                                                                                                                                          +
 AS 'pg_net', $function$_encode_url_with_params_array$function$                                                                                                                                                                      +
 
 CREATE OR REPLACE FUNCTION net._http_collect_response(request_id bigint, async boolean DEFAULT true)                                                                                                                                +
  RETURNS net.http_response_result                                                                                                                                                                                                   +
  LANGUAGE plpgsql                                                                                                                                                                                                                   +
 AS $function$                                                                                                                                                                                                                       +
 declare                                                                                                                                                                                                                             +
     rec net._http_response;                                                                                                                                                                                                         +
     req_exists boolean;                                                                                                                                                                                                             +
 begin                                                                                                                                                                                                                               +
                                                                                                                                                                                                                                     +
     if not async then                                                                                                                                                                                                               +
         perform net._await_response(request_id);                                                                                                                                                                                    +
     end if;                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                     +
     select *                                                                                                                                                                                                                        +
     into rec                                                                                                                                                                                                                        +
     from net._http_response                                                                                                                                                                                                         +
     where id = request_id;                                                                                                                                                                                                          +
                                                                                                                                                                                                                                     +
     if rec is null or rec.error_msg is not null then                                                                                                                                                                                +
         -- The request is either still processing or the request_id provided does not exist                                                                                                                                         +
                                                                                                                                                                                                                                     +
         -- TODO: request in progress is indistinguishable from request that doesn't exist                                                                                                                                           +
                                                                                                                                                                                                                                     +
         -- No request matching request_id found                                                                                                                                                                                     +
         return (                                                                                                                                                                                                                    +
             'ERROR',                                                                                                                                                                                                                +
             coalesce(rec.error_msg, 'request matching request_id not found'),                                                                                                                                                       +
             null                                                                                                                                                                                                                    +
         )::net.http_response_result;                                                                                                                                                                                                +
                                                                                                                                                                                                                                     +
     end if;                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                     +
     -- Return a valid, populated http_response_result                                                                                                                                                                               +
     return (                                                                                                                                                                                                                        +
         'SUCCESS',                                                                                                                                                                                                                  +
         'ok',                                                                                                                                                                                                                       +
         (                                                                                                                                                                                                                           +
             rec.status_code,                                                                                                                                                                                                        +
             rec.headers,                                                                                                                                                                                                            +
             rec.content                                                                                                                                                                                                             +
         )::net.http_response                                                                                                                                                                                                        +
     )::net.http_response_result;                                                                                                                                                                                                    +
 end;                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                          +
 
 CREATE OR REPLACE FUNCTION net._urlencode_string(string character varying)                                                                                                                                                          +
  RETURNS text                                                                                                                                                                                                                       +
  LANGUAGE c                                                                                                                                                                                                                         +
  IMMUTABLE                                                                                                                                                                                                                          +
 AS 'pg_net', $function$_urlencode_string$function$                                                                                                                                                                                  +
 
 CREATE OR REPLACE FUNCTION net.check_worker_is_up()                                                                                                                                                                                 +
  RETURNS void                                                                                                                                                                                                                       +
  LANGUAGE plpgsql                                                                                                                                                                                                                   +
 AS $function$                                                                                                                                                                                                                       +
 begin                                                                                                                                                                                                                               +
   if not exists (select pid from pg_stat_activity where backend_type ilike '%pg_net%') then                                                                                                                                         +
     raise exception using                                                                                                                                                                                                           +
       message = 'the pg_net background worker is not up'                                                                                                                                                                            +
     , detail  = 'the pg_net background worker is down due to an internal error and cannot process requests'                                                                                                                         +
     , hint    = 'make sure that you didn''t modify any of pg_net internal tables';                                                                                                                                                  +
   end if;                                                                                                                                                                                                                           +
 end                                                                                                                                                                                                                                 +
 $function$                                                                                                                                                                                                                          +
 
 CREATE OR REPLACE FUNCTION net.http_collect_response(request_id bigint, async boolean DEFAULT true)                                                                                                                                 +
  RETURNS net.http_response_result                                                                                                                                                                                                   +
  LANGUAGE plpgsql                                                                                                                                                                                                                   +
 AS $function$                                                                                                                                                                                                                       +
 begin                                                                                                                                                                                                                               +
   raise notice 'The net.http_collect_response function is deprecated.';                                                                                                                                                             +
   select net._http_collect_response(request_id, async);                                                                                                                                                                             +
 end;                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                          +
 
 CREATE OR REPLACE FUNCTION net.http_delete(url text, params jsonb DEFAULT '{}'::jsonb, headers jsonb DEFAULT '{}'::jsonb, timeout_milliseconds integer DEFAULT 5000, body jsonb DEFAULT NULL::jsonb)                                +
  RETURNS bigint                                                                                                                                                                                                                     +
  LANGUAGE plpgsql                                                                                                                                                                                                                   +
 AS $function$                                                                                                                                                                                                                       +
 declare                                                                                                                                                                                                                             +
     request_id bigint;                                                                                                                                                                                                              +
     params_array text[];                                                                                                                                                                                                            +
 begin                                                                                                                                                                                                                               +
     select coalesce(array_agg(net._urlencode_string(key) || '=' || net._urlencode_string(value)), '{}')                                                                                                                             +
     into params_array                                                                                                                                                                                                               +
     from jsonb_each_text(params);                                                                                                                                                                                                   +
                                                                                                                                                                                                                                     +
     -- Add to the request queue                                                                                                                                                                                                     +
     insert into net.http_request_queue(method, url, headers, body, timeout_milliseconds)                                                                                                                                            +
     values (                                                                                                                                                                                                                        +
         'DELETE',                                                                                                                                                                                                                   +
         net._encode_url_with_params_array(url, params_array),                                                                                                                                                                       +
         headers,                                                                                                                                                                                                                    +
         convert_to(body::text, 'UTF8'),                                                                                                                                                                                             +
         timeout_milliseconds                                                                                                                                                                                                        +
     )                                                                                                                                                                                                                               +
     returning id                                                                                                                                                                                                                    +
     into request_id;                                                                                                                                                                                                                +
                                                                                                                                                                                                                                     +
     perform net.wake();                                                                                                                                                                                                             +
                                                                                                                                                                                                                                     +
     return request_id;                                                                                                                                                                                                              +
 end                                                                                                                                                                                                                                 +
 $function$                                                                                                                                                                                                                          +
 
 CREATE OR REPLACE FUNCTION net.http_get(url text, params jsonb DEFAULT '{}'::jsonb, headers jsonb DEFAULT '{}'::jsonb, timeout_milliseconds integer DEFAULT 5000)                                                                   +
  RETURNS bigint                                                                                                                                                                                                                     +
  LANGUAGE plpgsql                                                                                                                                                                                                                   +
  SECURITY DEFINER                                                                                                                                                                                                                   +
  SET search_path TO 'net'                                                                                                                                                                                                           +
 AS $function$                                                                                                                                                                                                                       +
 declare                                                                                                                                                                                                                             +
     request_id bigint;                                                                                                                                                                                                              +
     params_array text[];                                                                                                                                                                                                            +
 begin                                                                                                                                                                                                                               +
     select coalesce(array_agg(net._urlencode_string(key) || '=' || net._urlencode_string(value)), '{}')                                                                                                                             +
     into params_array                                                                                                                                                                                                               +
     from jsonb_each_text(params);                                                                                                                                                                                                   +
                                                                                                                                                                                                                                     +
     -- Add to the request queue                                                                                                                                                                                                     +
     insert into net.http_request_queue(method, url, headers, timeout_milliseconds)                                                                                                                                                  +
     values (                                                                                                                                                                                                                        +
         'GET',                                                                                                                                                                                                                      +
         net._encode_url_with_params_array(url, params_array),                                                                                                                                                                       +
         headers,                                                                                                                                                                                                                    +
         timeout_milliseconds                                                                                                                                                                                                        +
     )                                                                                                                                                                                                                               +
     returning id                                                                                                                                                                                                                    +
     into request_id;                                                                                                                                                                                                                +
                                                                                                                                                                                                                                     +
     perform net.wake();                                                                                                                                                                                                             +
                                                                                                                                                                                                                                     +
     return request_id;                                                                                                                                                                                                              +
 end                                                                                                                                                                                                                                 +
 $function$                                                                                                                                                                                                                          +
 
 CREATE OR REPLACE FUNCTION net.http_post(url text, body jsonb DEFAULT '{}'::jsonb, params jsonb DEFAULT '{}'::jsonb, headers jsonb DEFAULT '{"Content-Type": "application/json"}'::jsonb, timeout_milliseconds integer DEFAULT 5000)+
  RETURNS bigint                                                                                                                                                                                                                     +
  LANGUAGE plpgsql                                                                                                                                                                                                                   +
  SECURITY DEFINER                                                                                                                                                                                                                   +
  SET search_path TO 'net'                                                                                                                                                                                                           +
 AS $function$                                                                                                                                                                                                                       +
 declare                                                                                                                                                                                                                             +
     request_id bigint;                                                                                                                                                                                                              +
     params_array text[];                                                                                                                                                                                                            +
     content_type text;                                                                                                                                                                                                              +
 begin                                                                                                                                                                                                                               +
                                                                                                                                                                                                                                     +
     -- Exctract the content_type from headers                                                                                                                                                                                       +
     select                                                                                                                                                                                                                          +
         header_value into content_type                                                                                                                                                                                              +
     from                                                                                                                                                                                                                            +
         jsonb_each_text(coalesce(headers, '{}'::jsonb)) r(header_name, header_value)                                                                                                                                                +
     where                                                                                                                                                                                                                           +
         lower(header_name) = 'content-type'                                                                                                                                                                                         +
     limit                                                                                                                                                                                                                           +
         1;                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                     +
     -- If the user provided new headers and omitted the content type                                                                                                                                                                +
     -- add it back in automatically                                                                                                                                                                                                 +
     if content_type is null then                                                                                                                                                                                                    +
         select headers || '{"Content-Type": "application/json"}'::jsonb into headers;                                                                                                                                               +
     end if;                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                     +
     -- Confirm that the content-type is set as "application/json"                                                                                                                                                                   +
     if content_type <> 'application/json' then                                                                                                                                                                                      +
         raise exception 'Content-Type header must be "application/json"';                                                                                                                                                           +
     end if;                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                     +
     select                                                                                                                                                                                                                          +
         coalesce(array_agg(net._urlencode_string(key) || '=' || net._urlencode_string(value)), '{}')                                                                                                                                +
     into                                                                                                                                                                                                                            +
         params_array                                                                                                                                                                                                                +
     from                                                                                                                                                                                                                            +
         jsonb_each_text(params);                                                                                                                                                                                                    +
                                                                                                                                                                                                                                     +
     -- Add to the request queue                                                                                                                                                                                                     +
     insert into net.http_request_queue(method, url, headers, body, timeout_milliseconds)                                                                                                                                            +
     values (                                                                                                                                                                                                                        +
         'POST',                                                                                                                                                                                                                     +
         net._encode_url_with_params_array(url, params_array),                                                                                                                                                                       +
         headers,                                                                                                                                                                                                                    +
         convert_to(body::text, 'UTF8'),                                                                                                                                                                                             +
         timeout_milliseconds                                                                                                                                                                                                        +
     )                                                                                                                                                                                                                               +
     returning id                                                                                                                                                                                                                    +
     into request_id;                                                                                                                                                                                                                +
                                                                                                                                                                                                                                     +
     perform net.wake();                                                                                                                                                                                                             +
                                                                                                                                                                                                                                     +
     return request_id;                                                                                                                                                                                                              +
 end                                                                                                                                                                                                                                 +
 $function$                                                                                                                                                                                                                          +
 
 CREATE OR REPLACE FUNCTION net.wait_until_running()                                                                                                                                                                                 +
  RETURNS void                                                                                                                                                                                                                       +
  LANGUAGE c                                                                                                                                                                                                                         +
 AS 'pg_net', $function$wait_until_running$function$                                                                                                                                                                                 +
 
 CREATE OR REPLACE FUNCTION net.wake()                                                                                                                                                                                               +
  RETURNS void                                                                                                                                                                                                                       +
  LANGUAGE c                                                                                                                                                                                                                         +
 AS 'pg_net', $function$wake$function$                                                                                                                                                                                               +
 
 CREATE OR REPLACE FUNCTION net.worker_restart()                                                                                                                                                                                     +
  RETURNS boolean                                                                                                                                                                                                                    +
  LANGUAGE c                                                                                                                                                                                                                         +
 AS 'pg_net', $function$worker_restart$function$                                                                                                                                                                                     +
 
(12 rows)
