# Prometheus Configuration for TenantFlow
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tenantflow-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker containers monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # TenantFlow Frontend Metrics
  - job_name: 'tenantflow-frontend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:3004']  # Adjust port as needed
    scrape_interval: 30s
    scrape_timeout: 10s

  # TenantFlow Backend Metrics
  - job_name: 'tenantflow-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3001']  # Adjust port as needed
    scrape_interval: 30s
    scrape_timeout: 10s

  # Auth Health Check Endpoint
  - job_name: 'auth-health'
    metrics_path: '/api/auth/metrics'
    static_configs:
      - targets: ['host.docker.internal:3004']
    scrape_interval: 60s
    scrape_timeout: 10s

  # Blackbox Exporter - Endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://tenantflow.app
          - https://api.tenantflow.app/health
          - https://tenantflow.app/api/auth/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']