/**
 * Standardized Lease Signature Error Constants
 *
 * Centralized error codes and messages for consistent error handling across the lease signature service.
 * Following the same pattern as stripe-errors.ts for consistency.
 */

/**
 * Lease signature error codes
 */
export const LEASE_SIGNATURE_ERROR_CODES = {
	// Not Found Errors
	LEASE_NOT_FOUND: 'lease_not_found',
	TENANT_NOT_FOUND: 'tenant_not_found',
	LEASE_NO_OWNER: 'lease_no_owner',

	// Authorization Errors
	NOT_LEASE_OWNER: 'not_lease_owner',
	NOT_ASSIGNED_TO_LEASE: 'not_assigned_to_lease',
	NO_ACCESS_TO_LEASE: 'no_access_to_lease',

	// Status Validation Errors
	LEASE_NOT_DRAFT: 'lease_not_draft',
	LEASE_NOT_PENDING_SIGNATURE: 'lease_not_pending_signature',
	LEASE_INVALID_STATUS_FOR_SIGNING: 'lease_invalid_status_for_signing',
	LEASE_NOT_PENDING_FOR_ACTIVATION: 'lease_not_pending_for_activation',

	// Email Validation Errors
	OWNER_EMAIL_MISSING: 'owner_email_missing',
	TENANT_EMAIL_MISSING: 'tenant_email_missing',

	// Signature State Errors
	OWNER_ALREADY_SIGNED: 'owner_already_signed',
	TENANT_ALREADY_SIGNED: 'tenant_already_signed',
	OWNER_NOT_SIGNED: 'owner_not_signed',
	TENANT_NOT_SIGNED: 'tenant_not_signed',

	// Activation Requirements
	LEASE_NEEDS_OWNER_TO_ACTIVATE: 'lease_needs_owner_to_activate',
	STRIPE_CONNECT_NOT_SETUP: 'stripe_connect_not_setup',
	STRIPE_VERIFICATION_INCOMPLETE: 'stripe_verification_incomplete',

	// Operation Failures
	SEND_FOR_SIGNATURE_FAILED: 'send_for_signature_failed',
	RECORD_SIGNATURE_FAILED: 'record_signature_failed',
	SIGN_LEASE_FAILED: 'sign_lease_failed',
	ACTIVATE_LEASE_FAILED: 'activate_lease_failed',
	CANCEL_SIGNATURE_FAILED: 'cancel_signature_failed',

	// System Errors
	RPC_NO_RESULT: 'rpc_no_result',
	FRONTEND_LOAD_FAILED: 'frontend_load_failed'
} as const

/**
 * User-friendly error messages mapped to error codes
 */
export const LEASE_SIGNATURE_ERROR_MESSAGES = {
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NOT_FOUND]: 'Lease not found.',
	[LEASE_SIGNATURE_ERROR_CODES.TENANT_NOT_FOUND]: 'Tenant not found.',
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NO_OWNER]: 'Lease has no owner assigned.',

	[LEASE_SIGNATURE_ERROR_CODES.NOT_LEASE_OWNER]: 'You do not own this lease.',
	[LEASE_SIGNATURE_ERROR_CODES.NOT_ASSIGNED_TO_LEASE]:
		'You are not assigned to this lease.',
	[LEASE_SIGNATURE_ERROR_CODES.NO_ACCESS_TO_LEASE]:
		'You do not have access to this lease.',

	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NOT_DRAFT]:
		'Only draft leases can be sent for signature.',
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NOT_PENDING_SIGNATURE]:
		'Only pending signature leases can be cancelled.',
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_INVALID_STATUS_FOR_SIGNING]:
		'Lease cannot be signed in its current status.',
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NOT_PENDING_FOR_ACTIVATION]:
		'Lease must be pending signature to activate.',

	[LEASE_SIGNATURE_ERROR_CODES.OWNER_EMAIL_MISSING]:
		'Cannot send lease for signature: property owner email is missing.',
	[LEASE_SIGNATURE_ERROR_CODES.TENANT_EMAIL_MISSING]:
		'Cannot send lease for signature: tenant email is missing.',

	[LEASE_SIGNATURE_ERROR_CODES.OWNER_ALREADY_SIGNED]:
		'Owner has already signed this lease.',
	[LEASE_SIGNATURE_ERROR_CODES.TENANT_ALREADY_SIGNED]:
		'Tenant has already signed this lease.',
	[LEASE_SIGNATURE_ERROR_CODES.OWNER_NOT_SIGNED]:
		'Owner has not signed the lease.',
	[LEASE_SIGNATURE_ERROR_CODES.TENANT_NOT_SIGNED]:
		'Tenant has not signed the lease.',

	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NEEDS_OWNER_TO_ACTIVATE]:
		'Lease must have a property owner to activate.',
	[LEASE_SIGNATURE_ERROR_CODES.STRIPE_CONNECT_NOT_SETUP]:
		'Property owner must have Stripe Connect setup to activate lease.',
	[LEASE_SIGNATURE_ERROR_CODES.STRIPE_VERIFICATION_INCOMPLETE]:
		'Property owner must complete Stripe Connect verification before lease can be activated. Please complete Stripe onboarding to enable payments.',

	[LEASE_SIGNATURE_ERROR_CODES.SEND_FOR_SIGNATURE_FAILED]:
		'Failed to send lease for signature.',
	[LEASE_SIGNATURE_ERROR_CODES.RECORD_SIGNATURE_FAILED]:
		'Failed to record signature.',
	[LEASE_SIGNATURE_ERROR_CODES.SIGN_LEASE_FAILED]: 'Failed to sign lease.',
	[LEASE_SIGNATURE_ERROR_CODES.ACTIVATE_LEASE_FAILED]:
		'Failed to activate lease.',
	[LEASE_SIGNATURE_ERROR_CODES.CANCEL_SIGNATURE_FAILED]:
		'Failed to cancel signature request.',

	[LEASE_SIGNATURE_ERROR_CODES.RPC_NO_RESULT]:
		'Service temporarily unavailable.',
	[LEASE_SIGNATURE_ERROR_CODES.FRONTEND_LOAD_FAILED]:
		'Unable to load signature status.'
} as const

/**
 * Error categories for monitoring
 */
export const LEASE_SIGNATURE_ERROR_CATEGORIES = {
	NOT_FOUND: 'not_found',
	AUTHORIZATION: 'authorization',
	VALIDATION: 'validation',
	BUSINESS_LOGIC: 'business_logic',
	SYSTEM: 'system',
	EXTERNAL_SERVICE: 'external_service'
} as const

/**
 * Error category mapping
 */
export const LEASE_SIGNATURE_ERROR_CATEGORY_MAP = {
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NOT_FOUND]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.NOT_FOUND,
	[LEASE_SIGNATURE_ERROR_CODES.TENANT_NOT_FOUND]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.NOT_FOUND,
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NO_OWNER]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.NOT_FOUND,

	[LEASE_SIGNATURE_ERROR_CODES.NOT_LEASE_OWNER]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.AUTHORIZATION,
	[LEASE_SIGNATURE_ERROR_CODES.NOT_ASSIGNED_TO_LEASE]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.AUTHORIZATION,
	[LEASE_SIGNATURE_ERROR_CODES.NO_ACCESS_TO_LEASE]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.AUTHORIZATION,

	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NOT_DRAFT]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.VALIDATION,
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NOT_PENDING_SIGNATURE]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.VALIDATION,
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_INVALID_STATUS_FOR_SIGNING]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.VALIDATION,
	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NOT_PENDING_FOR_ACTIVATION]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.VALIDATION,

	[LEASE_SIGNATURE_ERROR_CODES.OWNER_EMAIL_MISSING]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.VALIDATION,
	[LEASE_SIGNATURE_ERROR_CODES.TENANT_EMAIL_MISSING]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.VALIDATION,

	[LEASE_SIGNATURE_ERROR_CODES.OWNER_ALREADY_SIGNED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.BUSINESS_LOGIC,
	[LEASE_SIGNATURE_ERROR_CODES.TENANT_ALREADY_SIGNED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.BUSINESS_LOGIC,
	[LEASE_SIGNATURE_ERROR_CODES.OWNER_NOT_SIGNED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.BUSINESS_LOGIC,
	[LEASE_SIGNATURE_ERROR_CODES.TENANT_NOT_SIGNED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.BUSINESS_LOGIC,

	[LEASE_SIGNATURE_ERROR_CODES.LEASE_NEEDS_OWNER_TO_ACTIVATE]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.BUSINESS_LOGIC,
	[LEASE_SIGNATURE_ERROR_CODES.STRIPE_CONNECT_NOT_SETUP]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.EXTERNAL_SERVICE,
	[LEASE_SIGNATURE_ERROR_CODES.STRIPE_VERIFICATION_INCOMPLETE]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.EXTERNAL_SERVICE,

	[LEASE_SIGNATURE_ERROR_CODES.SEND_FOR_SIGNATURE_FAILED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.SYSTEM,
	[LEASE_SIGNATURE_ERROR_CODES.RECORD_SIGNATURE_FAILED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.SYSTEM,
	[LEASE_SIGNATURE_ERROR_CODES.SIGN_LEASE_FAILED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.SYSTEM,
	[LEASE_SIGNATURE_ERROR_CODES.ACTIVATE_LEASE_FAILED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.SYSTEM,
	[LEASE_SIGNATURE_ERROR_CODES.CANCEL_SIGNATURE_FAILED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.SYSTEM,

	[LEASE_SIGNATURE_ERROR_CODES.RPC_NO_RESULT]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.SYSTEM,
	[LEASE_SIGNATURE_ERROR_CODES.FRONTEND_LOAD_FAILED]:
		LEASE_SIGNATURE_ERROR_CATEGORIES.SYSTEM
} as const

// Type exports
export type LeaseSignatureErrorCode =
	(typeof LEASE_SIGNATURE_ERROR_CODES)[keyof typeof LEASE_SIGNATURE_ERROR_CODES]
export type LeaseSignatureErrorCategory =
	(typeof LEASE_SIGNATURE_ERROR_CATEGORIES)[keyof typeof LEASE_SIGNATURE_ERROR_CATEGORIES]
