"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BUSINESS_ERROR_CODES = exports.API_ERROR_MESSAGES = exports.API_ERROR_CODES = void 0;
exports.API_ERROR_CODES = {
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504
};
exports.API_ERROR_MESSAGES = {
    VALIDATION_FAILED: 'Validation failed',
    UNAUTHORIZED_ACCESS: 'Unauthorized access',
    RESOURCE_NOT_FOUND: 'Resource not found',
    INTERNAL_ERROR: 'Internal server error',
    BAD_REQUEST: 'Bad request',
    FORBIDDEN: 'Access forbidden',
    CONFLICT: 'Resource conflict',
    TOO_MANY_REQUESTS: 'Too many requests',
    SERVICE_UNAVAILABLE: 'Service temporarily unavailable'
};
exports.BUSINESS_ERROR_CODES = {
    PROPERTY_NOT_FOUND: 'PROPERTY_NOT_FOUND',
    UNIT_NOT_AVAILABLE: 'UNIT_NOT_AVAILABLE',
    TENANT_ALREADY_EXISTS: 'TENANT_ALREADY_EXISTS',
    LEASE_OVERLAP: 'LEASE_OVERLAP',
    INVALID_LEASE_DATES: 'INVALID_LEASE_DATES',
    MAINTENANCE_REQUEST_CLOSED: 'MAINTENANCE_REQUEST_CLOSED',
    BILLING_ERROR: 'BILLING_ERROR',
    SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
    INVALID_CSV_FORMAT: 'INVALID_CSV_FORMAT',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',
    CSV_MISSING_REQUIRED_COLUMNS: 'CSV_MISSING_REQUIRED_COLUMNS',
    CSV_INVALID_DATA: 'CSV_INVALID_DATA',
    CSV_DUPLICATE_ENTRIES: 'CSV_DUPLICATE_ENTRIES',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
    NETWORK_ERROR: 'NETWORK_ERROR',
    CORS_ERROR: 'CORS_ERROR'
};
//# sourceMappingURL=api-errors.js.map