export const SORT_ORDER = {
    ASC: 'asc',
    DESC: 'desc'
};
export const DOCUMENT_TYPE = {
    LEASE: 'LEASE',
    INVOICE: 'INVOICE',
    RECEIPT: 'RECEIPT',
    INSPECTION: 'INSPECTION',
    PHOTO: 'PHOTO',
    INSURANCE: 'INSURANCE',
    OTHER: 'OTHER'
};
export const NOTIFICATION_TYPE = {
    RENT_DUE: 'RENT_DUE',
    LEASE_EXPIRING: 'LEASE_EXPIRING',
    MAINTENANCE_REQUEST: 'MAINTENANCE_REQUEST',
    MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
    NEW_TENANT: 'NEW_TENANT',
    TENANT_MOVED_OUT: 'TENANT_MOVED_OUT',
    PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
    SUBSCRIPTION_EXPIRING: 'SUBSCRIPTION_EXPIRING',
    SYSTEM_ALERT: 'SYSTEM_ALERT'
};
//# sourceMappingURL=common.js.map