export const PROPERTY_TYPE = {
    SINGLE_FAMILY: 'SINGLE_FAMILY',
    MULTI_FAMILY: 'MULTI_FAMILY',
    APARTMENT: 'APARTMENT',
    CONDO: 'CONDO',
    TOWNHOUSE: 'TOWNHOUSE',
    COMMERCIAL: 'COMMERCIAL'
};
export const UNIT_STATUS = {
    AVAILABLE: 'AVAILABLE',
    OCCUPIED: 'OCCUPIED',
    MAINTENANCE: 'MAINTENANCE',
    VACANT: 'VACANT'
};
//# sourceMappingURL=properties.js.map