# Chromatic Configuration for Visual Regression Testing
# Documentation: https://www.chromatic.com/docs/configuration

# Project configuration
projectId: "689cf99e73396c4c66b53bd0"

# Build configuration
buildScriptName: "build-storybook"
storybookBuildDir: "storybook-static"

# Performance optimizations
zip: true
onlyChanged: true # TurboSnap - only test changed components
traceChanged: "expanded"

# Ignore patterns for TurboSnap
untraced:
  - "node_modules/**"
  - ".turbo/**"
  - "coverage/**"
  - "*.log"
  - "*.tmp"

# Auto-accept changes on main branch
autoAcceptChanges: "main"

# Exit with code 0 even if there are visual changes
exitZeroOnChanges: true

# Skip builds for certain branches/conditions
skip:
  - "dependabot/**"
  - "**/**/renovate/**"

# Visual diff configuration
threshold: 0.2 # Allow 20% difference for minor rendering variations

# Viewport configuration for comprehensive testing
viewports:
  - name: "Mobile Portrait"
    width: 375
    height: 667
  - name: "Mobile Landscape" 
    width: 667
    height: 375
  - name: "Tablet Portrait"
    width: 768
    height: 1024
  - name: "Tablet Landscape"
    width: 1024
    height: 768
  - name: "Desktop Small"
    width: 1366
    height: 768
  - name: "Desktop Large"
    width: 1920
    height: 1080

# Browser configuration
browsers:
  - chrome
  # Add more browsers as needed:
  # - firefox
  # - safari
  # - edge

# Storybook-specific configuration
storybookConfigDir: ".storybook"

# Parallel builds for faster processing
parallel: 4

# Debugging options (disabled for production)
debug: false
diagnostics: false

# Upload configuration
uploadMaxRetries: 3
uploadTimeout: 600000 # 10 minutes

# Branch configuration
baseBranches:
  - "main"
  - "develop"

# Notification settings (can be configured in Chromatic dashboard)
# notifications:
#   - email
#   - slack
#   - webhook