// Backend Types Bridge  
// This file defines the AppRouter type by importing from the built backend
// Auto-generated by sync-trpc-types.ts - DO NOT EDIT MANUALLY
// Generated on: 2025-07-26T06:44:30.000Z

import type { inferRouterInputs, inferRouterOutputs } from '@trpc/server'

// Import the actual AppRouter type from the built backend
// This is the proper way to get the router type from the factory function
export type AppRouter = import('../../../apps/backend/dist/trpc/app-router').AppRouter

// Re-export TRPC type utilities for easy access
export type { inferRouterInputs, inferRouterOutputs }

// Type aliases for easier use in frontend
export type RouterInputs = inferRouterInputs<AppRouter>
export type RouterOutputs = inferRouterOutputs<AppRouter>