// Backend Types Bridge  
// This file imports actual TRPC types from the backend build
// Auto-generated by sync-trpc-types.ts - DO NOT EDIT MANUALLY
// Generated on: 2025-07-26T00:32:01.124Z

// Import the AppRouter type directly from the backend
// The backend exports this as a proper TRPC router type
import type { AppRouter } from '@tenantflow/backend/trpc'
import type { inferRouterInputs, inferRouterOutputs } from '@trpc/server'

// Re-export the AppRouter type
export type { AppRouter }

// Re-export TRPC type utilities for easy access
export type { inferRouterInputs, inferRouterOutputs }

// Type aliases for easier use in frontend
export type RouterInputs = inferRouterInputs<AppRouter>
export type RouterOutputs = inferRouterOutputs<AppRouter>
