"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateUserMessage = exports.createStandardizedError = exports.toClientSafeError = exports.calculateRetryDelay = exports.getErrorSeverity = exports.getErrorCategory = exports.generateErrorId = exports.StripeUtils = exports.isStripePriceId = exports.isStripeSubscriptionId = exports.isStripeCustomerId = exports.isStripeId = exports.isCriticalError = exports.isConfigurationError = exports.isInfrastructureError = exports.isRateLimitError = exports.isCardError = exports.isStripeRetryableError = exports.isStripeConfig = exports.isPlanConfig = exports.isUserSubscription = exports.isPaymentMethod = exports.isStripeWebhookEvent = exports.isStandardizedStripeError = exports.isStripeErrorCode = exports.isWebhookEventType = exports.isSubscriptionStatus = exports.isBillingPeriod = exports.isPlanType = exports.StripeTypeGuards = exports.RETRYABLE_ERROR_CODES = exports.ERROR_SEVERITY_MAPPING = exports.ERROR_CATEGORY_MAPPING = exports.DEFAULT_STRIPE_RETRY_CONFIG = exports.WEBHOOK_EVENT_TYPES = exports.STRIPE_ERROR_SEVERITIES = exports.STRIPE_ERROR_CATEGORIES = exports.STRIPE_DECLINE_CODES = exports.STRIPE_ERROR_CODES = exports.STRIPE_API_VERSIONS = exports.SUBSCRIPTION_STATUSES = exports.BILLING_PERIODS = exports.PLAN_TYPES = exports.validatePricingPlan = exports.getStripeErrorMessage = exports.calculateYearlySavings = exports.formatPrice = exports.getReminderStatusColor = exports.getReminderStatusLabel = exports.getReminderTypeLabel = void 0;
exports.ERROR_TYPES = exports.getErrorLogLevel = exports.isRetryableError = exports.classifyError = exports.createBusinessLogicError = exports.createNetworkError = exports.createValidationError = exports.createStandardError = exports.SUBSCRIPTION_URLS = exports.calculateAnnualSavings = exports.calculateAnnualPrice = exports.calculateProratedAmount = exports.getLegacyPlanById = exports.REMINDER_STATUS = exports.REMINDER_TYPE = exports.TENANT_STATUS = exports.PLAN_IDS = exports.validatePricingPlans = exports.getPaidPlans = exports.getFreePlan = exports.getRecommendedPlan = exports.getPlanById = exports.PRICING_PLANS = exports.STRIPE_ERRORS = exports.PLAN_TYPE = exports.generateIdempotencyKey = exports.sanitizeMetadata = exports.validateStripeConfig = exports.getTrialDaysRemaining = exports.getDaysUntilExpiry = exports.getSubscriptionStatusDisplay = exports.isInGracePeriod = exports.isActiveSubscription = exports.getPlanDisplayName = exports.calculateStripeAnnualSavings = exports.formatLegacyPrice = exports.getBillingPeriodFromPriceId = exports.getPlanTypeFromPriceId = void 0;
var reminders_1 = require("./types/reminders");
Object.defineProperty(exports, "getReminderTypeLabel", { enumerable: true, get: function () { return reminders_1.getReminderTypeLabel; } });
Object.defineProperty(exports, "getReminderStatusLabel", { enumerable: true, get: function () { return reminders_1.getReminderStatusLabel; } });
Object.defineProperty(exports, "getReminderStatusColor", { enumerable: true, get: function () { return reminders_1.getReminderStatusColor; } });
var stripe_pricing_1 = require("./types/stripe-pricing");
Object.defineProperty(exports, "formatPrice", { enumerable: true, get: function () { return stripe_pricing_1.formatPrice; } });
Object.defineProperty(exports, "calculateYearlySavings", { enumerable: true, get: function () { return stripe_pricing_1.calculateYearlySavings; } });
Object.defineProperty(exports, "getStripeErrorMessage", { enumerable: true, get: function () { return stripe_pricing_1.getStripeErrorMessage; } });
Object.defineProperty(exports, "validatePricingPlan", { enumerable: true, get: function () { return stripe_pricing_1.validatePricingPlan; } });
var stripe_1 = require("./types/stripe");
Object.defineProperty(exports, "PLAN_TYPES", { enumerable: true, get: function () { return stripe_1.PLAN_TYPES; } });
Object.defineProperty(exports, "BILLING_PERIODS", { enumerable: true, get: function () { return stripe_1.BILLING_PERIODS; } });
Object.defineProperty(exports, "SUBSCRIPTION_STATUSES", { enumerable: true, get: function () { return stripe_1.SUBSCRIPTION_STATUSES; } });
Object.defineProperty(exports, "STRIPE_API_VERSIONS", { enumerable: true, get: function () { return stripe_1.STRIPE_API_VERSIONS; } });
Object.defineProperty(exports, "STRIPE_ERROR_CODES", { enumerable: true, get: function () { return stripe_1.STRIPE_ERROR_CODES; } });
Object.defineProperty(exports, "STRIPE_DECLINE_CODES", { enumerable: true, get: function () { return stripe_1.STRIPE_DECLINE_CODES; } });
Object.defineProperty(exports, "STRIPE_ERROR_CATEGORIES", { enumerable: true, get: function () { return stripe_1.STRIPE_ERROR_CATEGORIES; } });
Object.defineProperty(exports, "STRIPE_ERROR_SEVERITIES", { enumerable: true, get: function () { return stripe_1.STRIPE_ERROR_SEVERITIES; } });
Object.defineProperty(exports, "WEBHOOK_EVENT_TYPES", { enumerable: true, get: function () { return stripe_1.WEBHOOK_EVENT_TYPES; } });
Object.defineProperty(exports, "DEFAULT_STRIPE_RETRY_CONFIG", { enumerable: true, get: function () { return stripe_1.DEFAULT_STRIPE_RETRY_CONFIG; } });
Object.defineProperty(exports, "ERROR_CATEGORY_MAPPING", { enumerable: true, get: function () { return stripe_1.ERROR_CATEGORY_MAPPING; } });
Object.defineProperty(exports, "ERROR_SEVERITY_MAPPING", { enumerable: true, get: function () { return stripe_1.ERROR_SEVERITY_MAPPING; } });
Object.defineProperty(exports, "RETRYABLE_ERROR_CODES", { enumerable: true, get: function () { return stripe_1.RETRYABLE_ERROR_CODES; } });
var stripe_guards_1 = require("./types/stripe-guards");
Object.defineProperty(exports, "StripeTypeGuards", { enumerable: true, get: function () { return stripe_guards_1.StripeTypeGuards; } });
Object.defineProperty(exports, "isPlanType", { enumerable: true, get: function () { return stripe_guards_1.isPlanType; } });
Object.defineProperty(exports, "isBillingPeriod", { enumerable: true, get: function () { return stripe_guards_1.isBillingPeriod; } });
Object.defineProperty(exports, "isSubscriptionStatus", { enumerable: true, get: function () { return stripe_guards_1.isSubscriptionStatus; } });
Object.defineProperty(exports, "isWebhookEventType", { enumerable: true, get: function () { return stripe_guards_1.isWebhookEventType; } });
Object.defineProperty(exports, "isStripeErrorCode", { enumerable: true, get: function () { return stripe_guards_1.isStripeErrorCode; } });
Object.defineProperty(exports, "isStandardizedStripeError", { enumerable: true, get: function () { return stripe_guards_1.isStandardizedStripeError; } });
Object.defineProperty(exports, "isStripeWebhookEvent", { enumerable: true, get: function () { return stripe_guards_1.isStripeWebhookEvent; } });
Object.defineProperty(exports, "isPaymentMethod", { enumerable: true, get: function () { return stripe_guards_1.isPaymentMethod; } });
Object.defineProperty(exports, "isUserSubscription", { enumerable: true, get: function () { return stripe_guards_1.isUserSubscription; } });
Object.defineProperty(exports, "isPlanConfig", { enumerable: true, get: function () { return stripe_guards_1.isPlanConfig; } });
Object.defineProperty(exports, "isStripeConfig", { enumerable: true, get: function () { return stripe_guards_1.isStripeConfig; } });
Object.defineProperty(exports, "isStripeRetryableError", { enumerable: true, get: function () { return stripe_guards_1.isRetryableError; } });
Object.defineProperty(exports, "isCardError", { enumerable: true, get: function () { return stripe_guards_1.isCardError; } });
Object.defineProperty(exports, "isRateLimitError", { enumerable: true, get: function () { return stripe_guards_1.isRateLimitError; } });
Object.defineProperty(exports, "isInfrastructureError", { enumerable: true, get: function () { return stripe_guards_1.isInfrastructureError; } });
Object.defineProperty(exports, "isConfigurationError", { enumerable: true, get: function () { return stripe_guards_1.isConfigurationError; } });
Object.defineProperty(exports, "isCriticalError", { enumerable: true, get: function () { return stripe_guards_1.isCriticalError; } });
Object.defineProperty(exports, "isStripeId", { enumerable: true, get: function () { return stripe_guards_1.isStripeId; } });
Object.defineProperty(exports, "isStripeCustomerId", { enumerable: true, get: function () { return stripe_guards_1.isStripeCustomerId; } });
Object.defineProperty(exports, "isStripeSubscriptionId", { enumerable: true, get: function () { return stripe_guards_1.isStripeSubscriptionId; } });
Object.defineProperty(exports, "isStripePriceId", { enumerable: true, get: function () { return stripe_guards_1.isStripePriceId; } });
var stripe_utils_1 = require("./types/stripe-utils");
Object.defineProperty(exports, "StripeUtils", { enumerable: true, get: function () { return stripe_utils_1.StripeUtils; } });
Object.defineProperty(exports, "generateErrorId", { enumerable: true, get: function () { return stripe_utils_1.generateErrorId; } });
Object.defineProperty(exports, "getErrorCategory", { enumerable: true, get: function () { return stripe_utils_1.getErrorCategory; } });
Object.defineProperty(exports, "getErrorSeverity", { enumerable: true, get: function () { return stripe_utils_1.getErrorSeverity; } });
Object.defineProperty(exports, "calculateRetryDelay", { enumerable: true, get: function () { return stripe_utils_1.calculateRetryDelay; } });
Object.defineProperty(exports, "toClientSafeError", { enumerable: true, get: function () { return stripe_utils_1.toClientSafeError; } });
Object.defineProperty(exports, "createStandardizedError", { enumerable: true, get: function () { return stripe_utils_1.createStandardizedError; } });
Object.defineProperty(exports, "generateUserMessage", { enumerable: true, get: function () { return stripe_utils_1.generateUserMessage; } });
Object.defineProperty(exports, "getPlanTypeFromPriceId", { enumerable: true, get: function () { return stripe_utils_1.getPlanTypeFromPriceId; } });
Object.defineProperty(exports, "getBillingPeriodFromPriceId", { enumerable: true, get: function () { return stripe_utils_1.getBillingPeriodFromPriceId; } });
Object.defineProperty(exports, "formatLegacyPrice", { enumerable: true, get: function () { return stripe_utils_1.formatPrice; } });
Object.defineProperty(exports, "calculateStripeAnnualSavings", { enumerable: true, get: function () { return stripe_utils_1.calculateAnnualSavings; } });
Object.defineProperty(exports, "getPlanDisplayName", { enumerable: true, get: function () { return stripe_utils_1.getPlanDisplayName; } });
Object.defineProperty(exports, "isActiveSubscription", { enumerable: true, get: function () { return stripe_utils_1.isActiveSubscription; } });
Object.defineProperty(exports, "isInGracePeriod", { enumerable: true, get: function () { return stripe_utils_1.isInGracePeriod; } });
Object.defineProperty(exports, "getSubscriptionStatusDisplay", { enumerable: true, get: function () { return stripe_utils_1.getSubscriptionStatusDisplay; } });
Object.defineProperty(exports, "getDaysUntilExpiry", { enumerable: true, get: function () { return stripe_utils_1.getDaysUntilExpiry; } });
Object.defineProperty(exports, "getTrialDaysRemaining", { enumerable: true, get: function () { return stripe_utils_1.getTrialDaysRemaining; } });
Object.defineProperty(exports, "validateStripeConfig", { enumerable: true, get: function () { return stripe_utils_1.validateStripeConfig; } });
Object.defineProperty(exports, "sanitizeMetadata", { enumerable: true, get: function () { return stripe_utils_1.sanitizeMetadata; } });
Object.defineProperty(exports, "generateIdempotencyKey", { enumerable: true, get: function () { return stripe_utils_1.generateIdempotencyKey; } });
var billing_1 = require("./types/billing");
Object.defineProperty(exports, "PLAN_TYPE", { enumerable: true, get: function () { return billing_1.PLAN_TYPE; } });
Object.defineProperty(exports, "STRIPE_ERRORS", { enumerable: true, get: function () { return billing_1.STRIPE_ERRORS; } });
__exportStar(require("./constants"), exports);
var pricing_plans_1 = require("./constants/pricing-plans");
Object.defineProperty(exports, "PRICING_PLANS", { enumerable: true, get: function () { return pricing_plans_1.PRICING_PLANS; } });
Object.defineProperty(exports, "getPlanById", { enumerable: true, get: function () { return pricing_plans_1.getPlanById; } });
Object.defineProperty(exports, "getRecommendedPlan", { enumerable: true, get: function () { return pricing_plans_1.getRecommendedPlan; } });
Object.defineProperty(exports, "getFreePlan", { enumerable: true, get: function () { return pricing_plans_1.getFreePlan; } });
Object.defineProperty(exports, "getPaidPlans", { enumerable: true, get: function () { return pricing_plans_1.getPaidPlans; } });
Object.defineProperty(exports, "validatePricingPlans", { enumerable: true, get: function () { return pricing_plans_1.validatePricingPlans; } });
Object.defineProperty(exports, "PLAN_IDS", { enumerable: true, get: function () { return pricing_plans_1.PLAN_IDS; } });
var tenants_1 = require("./constants/tenants");
Object.defineProperty(exports, "TENANT_STATUS", { enumerable: true, get: function () { return tenants_1.TENANT_STATUS; } });
var reminders_2 = require("./constants/reminders");
Object.defineProperty(exports, "REMINDER_TYPE", { enumerable: true, get: function () { return reminders_2.REMINDER_TYPE; } });
Object.defineProperty(exports, "REMINDER_STATUS", { enumerable: true, get: function () { return reminders_2.REMINDER_STATUS; } });
var billing_2 = require("./utils/billing");
Object.defineProperty(exports, "getLegacyPlanById", { enumerable: true, get: function () { return billing_2.getPlanById; } });
Object.defineProperty(exports, "calculateProratedAmount", { enumerable: true, get: function () { return billing_2.calculateProratedAmount; } });
Object.defineProperty(exports, "calculateAnnualPrice", { enumerable: true, get: function () { return billing_2.calculateAnnualPrice; } });
Object.defineProperty(exports, "calculateAnnualSavings", { enumerable: true, get: function () { return billing_2.calculateAnnualSavings; } });
Object.defineProperty(exports, "SUBSCRIPTION_URLS", { enumerable: true, get: function () { return billing_2.SUBSCRIPTION_URLS; } });
var errors_1 = require("./utils/errors");
Object.defineProperty(exports, "createStandardError", { enumerable: true, get: function () { return errors_1.createStandardError; } });
Object.defineProperty(exports, "createValidationError", { enumerable: true, get: function () { return errors_1.createValidationError; } });
Object.defineProperty(exports, "createNetworkError", { enumerable: true, get: function () { return errors_1.createNetworkError; } });
Object.defineProperty(exports, "createBusinessLogicError", { enumerable: true, get: function () { return errors_1.createBusinessLogicError; } });
Object.defineProperty(exports, "classifyError", { enumerable: true, get: function () { return errors_1.classifyError; } });
Object.defineProperty(exports, "isRetryableError", { enumerable: true, get: function () { return errors_1.isRetryableError; } });
Object.defineProperty(exports, "getErrorLogLevel", { enumerable: true, get: function () { return errors_1.getErrorLogLevel; } });
Object.defineProperty(exports, "ERROR_TYPES", { enumerable: true, get: function () { return errors_1.ERROR_TYPES; } });
__exportStar(require("./validation"), exports);
