// TRPC Types Generated from Backend Router
// Auto-generated by sync-trpc-types.ts - DO NOT EDIT MANUALLY
// Generated on: 2025-07-26T06:43:35.490Z

import type { AppRouter, RouterInputs, RouterOutputs } from './backend-types'

// Re-export router types for convenience
export type { AppRouter, RouterInputs, RouterOutputs }

// Type aliases for convenience and backward compatibility
export type AppRouterType = AppRouter

// Note: Specific procedure input/output types cannot be defined with type stubs
// Use RouterInputs and RouterOutputs directly with proper type indexing:
// Example: RouterInputs['properties']['add'] for property creation input
// Example: RouterOutputs['auth']['me'] for authentication output
