// TRPC Types Generated from Backend Router
// Auto-generated by sync-trpc-types.ts - DO NOT EDIT MANUALLY
// Generated on: 2025-07-25T06:20:10.664Z

import type { AppRouter, RouterInputs, RouterOutputs } from './backend-types'

// Re-export router types for convenience
export type { AppRouter, RouterInputs, RouterOutputs }

// Specific procedure input types for easier usage
export type PropertyCreateInput = RouterInputs['properties']['add']
export type PropertyUpdateInput = RouterInputs['properties']['update']
export type TenantCreateInput = RouterInputs['tenants']['add']
export type TenantUpdateInput = RouterInputs['tenants']['update']
export type MaintenanceRequestInput = RouterInputs['maintenance']['add']
export type UnitCreateInput = RouterInputs['units']['add']
export type UnitUpdateInput = RouterInputs['units']['update']
export type LeaseCreateInput = RouterInputs['leases']['add']
export type LeaseUpdateInput = RouterInputs['leases']['update']

// Specific procedure output types for easier usage
export type PropertyOutput = RouterOutputs['properties']['byId']
export type PropertyListOutput = RouterOutputs['properties']['list']
export type TenantOutput = RouterOutputs['tenants']['byId']
export type TenantListOutput = RouterOutputs['tenants']['list']
export type MaintenanceRequestOutput = RouterOutputs['maintenance']['byId']
export type MaintenanceRequestListOutput = RouterOutputs['maintenance']['list']
export type UnitOutput = RouterOutputs['units']['byId']
export type UnitListOutput = RouterOutputs['units']['list']
export type LeaseOutput = RouterOutputs['leases']['byId']
export type LeaseListOutput = RouterOutputs['leases']['list']
export type SubscriptionOutput = RouterOutputs['subscriptions']['current']

// Authentication types
export type UserProfile = RouterOutputs['auth']['me']
export type UpdateProfileInput = RouterInputs['auth']['updateProfile']

// Subscription types
export type CheckoutSessionInput = RouterInputs['subscriptions']['createCheckoutSession']
export type PortalSessionInput = RouterInputs['subscriptions']['createPortalSession']

// Common query types
export type PaginationQueryInput = RouterInputs['properties']['list']
export type PropertyStatsOutput = RouterOutputs['properties']['stats']
export type TenantStatsOutput = RouterOutputs['tenants']['stats']
export type MaintenanceStatsOutput = RouterOutputs['maintenance']['stats']

// Re-export for convenience and backward compatibility
export type AppRouterType = AppRouter

// Export specific router types for modular imports
export type AuthRouter = AppRouter['auth']
export type PropertiesRouter = AppRouter['properties']
export type TenantsRouter = AppRouter['tenants']
export type MaintenanceRouter = AppRouter['maintenance']
export type UnitsRouter = AppRouter['units']
export type LeasesRouter = AppRouter['leases']
export type SubscriptionsRouter = AppRouter['subscriptions']

// Helper type to get all procedure names from a router
export type ProcedureNames<T> = keyof T

// Helper type to check if a procedure exists
export type HasProcedure<T, K extends string> = K extends keyof T ? true : false

// Type helper to extract procedure type
export type ProcedureType<
  TRouter,
  TProcedure extends keyof TRouter
> = TRouter[TProcedure]
