-- Create databases for all services
CREATE DATABASE IF NOT EXISTS n8n;
CREATE DATABASE IF NOT EXISTS nocodb;
CREATE DATABASE IF NOT EXISTS listmonk;
CREATE DATABASE IF NOT EXISTS penpot;

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE n8n TO postgres;
GRANT ALL PRIVILEGES ON DATABASE nocodb TO postgres;
GRANT ALL PRIVILEGES ON DATABASE listmonk TO postgres;
GRANT ALL PRIVILEGES ON DATABASE penpot TO postgres;