// File: scripts/generate-trpc-types.ts
// Purpose: Generate AppRouter type for tRPC and write to packages/shared/trpc.ts

import fs from "fs";
import path from "path";

const header = `// AUTO-GENERATED FILE. DO NOT EDIT.
// This file is generated by scripts/generate-trpc-types.ts
// It provides the AppRouter type for tRPC client/server type safety.

`;

const typeExport = `import type { createAppRouter } from "../../apps/backend/src/trpc/app-router";
export type AppRouter = ReturnType<typeof createAppRouter>;
`;

const outPath = path.resolve(__dirname, "../packages/shared/trpc.ts");

fs.writeFileSync(outPath, header + typeExport, "utf8");
console.log("AppRouter type written to packages/shared/trpc.ts");
