-- =============================================================================
-- Phase 66 - Rental Application Intake: the seven RPCs.
--
-- (a) THESE FUNCTIONS ARE THE ONLY WRITE PATHS INTO BOTH TABLES.
--     20260806120000_rental_applications_schema.sql creates
--     public.rental_application_links and public.rental_applications with
--     SELECT policies (and one owner DELETE policy on applications) and
--     deliberately NO INSERT POLICY AND NO UPDATE POLICY FOR ANY ROLE.
--
--     That is not an oversight in the schema and it is not something to "fix"
--     here. It means there is no PostgREST .insert() or .update() fallback for
--     anything in this phase: if an owner-side mutation does not have a function
--     in this file, that mutation has no path at all. The owner write surface is
--     exactly:
--
--       create a link          -> create_application_link
--       revoke a link          -> revoke_application_link
--       change status          -> set_application_status
--       decline with a reason  -> set_application_status(..., 'rejected', reason)
--       save owner notes       -> set_application_notes
--       record a conversion    -> record_application_conversion
--       delete an application  -> PostgREST DELETE, covered by the
--                                 rental_applications_delete policy in 66-01.
--                                 The one owner write that is NOT an RPC,
--                                 because a delete needs no field-level guard.
--
--     Reads stay on PostgREST through the SELECT policies. Nothing else writes.
--
-- (b) pgcrypto IS NOT IN `public` ON THIS PROJECT (D-15).
--     Verified against production on 2026-08-06: pgcrypto is installed in the
--     `extensions` schema and digest() exists ONLY there (digest_in_public = 0).
--     Every SECURITY DEFINER function below is pinned to search_path = public
--     per CLAUDE.md, so an UNQUALIFIED pgcrypto call inside one of them cannot
--     resolve. Both calls are therefore written as extensions.gen_random_bytes
--     and extensions.digest.
--
--     This is the single most dangerous line in the file, because the failure is
--     invisible until runtime: an unqualified call parses, the migration applies
--     clean, and the function then raises "function digest(text, unknown) does
--     not exist" the first time an owner clicks Create link in production.
--     66-RESEARCH.md's example is unqualified; CONTEXT D-15 outranks it. Plan
--     66-06 smoke-calls create_application_link against production precisely
--     because this is the one line the repo cannot prove.
--
--     gen_random_uuid() needs no qualification - it is core PostgreSQL (pgcrypto
--     only supplied it before v13), not an extensions-schema function.
--
-- (c) HOW THIS FILE REACHES PRODUCTION.
--     It is NOT applied by the plan that authors it. Plan 66-06 is the single
--     blocking, owner-gated apply step and runs it through Supabase MCP
--     apply_migration, then reconciles this filename to the prod-assigned
--     timestamp. Authoring and applying are separate on purpose: typecheck and
--     next build both pass against a stale generated src/types/supabase.ts, so
--     an unapplied migration produces a fully green CI. This project shipped
--     three of them that way in v9.0 (2026-07-17).
--
-- (d) EVERY FUNCTION CARRIES `revoke all ... from public` AHEAD OF ITS GRANT.
--     PostgreSQL auto-grants EXECUTE to PUBLIC at creation time, and both `anon`
--     and `authenticated` inherit PUBLIC. Without the revoke, a SECURITY DEFINER
--     function is executable by unauthenticated callers no matter what its body
--     checks. That is the regression class 20260529225039 was written to close
--     across 19 existing functions; this file does not reopen it.
--
--     A full grant ledger is at the foot of the file.
-- =============================================================================

-- =============================================================================
-- 1. create_application_link - mint the public link for one unit.
--
--    Owner-gated. The raw token is generated by the SERVER's CSPRNG and returned
--    to the caller once per creation; it is also stored (D-03a) so the owner can
--    re-copy the listing URL for as long as the link is active, without a
--    rotation that would silently break a listing already posted to Zillow.
-- =============================================================================
create or replace function public.create_application_link(
  p_unit_id      uuid,
  p_expires_days integer default 60
)
  returns table (link_id uuid, raw_token text, expires_at timestamptz)
  language plpgsql
  security definer
  set search_path = public
as $function$
declare
  v_owner   uuid := (select auth.uid());
  v_days    integer;
  v_raw     text;
  v_id      uuid;
  v_expires timestamptz;
begin
  if v_owner is null then
    raise exception 'not authenticated';
  end if;

  -- One message for "this unit does not exist" and "this unit is not yours".
  -- Two distinct messages would let any signed-in owner probe unit ids and learn
  -- which ones belong to somebody else (T-66-02).
  if not exists (
    select 1
    from public.units un
    where un.id = p_unit_id
      and un.owner_user_id = v_owner
  ) then
    raise exception 'unit not found';
  end if;

  -- Refuse while an ACTIVE link exists for this unit. Expired and revoked links
  -- do not block - UI-SPEC section C offers "Create a new link" in exactly those
  -- two states, and only "Revoke" while active.
  --
  -- This is what keeps "one active link per unit" true. It cannot be a partial
  -- unique index instead: the predicate needs now(), which is not immutable and
  -- therefore not indexable. It doubles as the double-click and race guard on
  -- the Create button.
  if exists (
    select 1
    from public.rental_application_links l
    where l.unit_id = p_unit_id
      and l.revoked_at is null
      and l.expires_at > now()
  ) then
    raise exception 'link already active';
  end if;

  -- Clamp rather than trust. An unbounded expiry turns a listing link into a
  -- permanent public write surface that nobody remembers exists, and a zero or
  -- negative value mints a link that is already dead - the owner would post it
  -- to a listing and never learn why no applications arrive.
  v_days := least(greatest(coalesce(p_expires_days, 60), 1), 365);

  -- 256 bits from the server's CSPRNG, hex-encoded. Never gen_random_uuid() as a
  -- token (122 bits of entropy and structured), never client-supplied entropy,
  -- and never a value that reached the server as a query parameter. See header
  -- note (b) for why this call is schema-qualified.
  v_raw     := encode(extensions.gen_random_bytes(32), 'hex');
  v_expires := now() + make_interval(days => v_days);

  insert into public.rental_application_links (
    unit_id,
    owner_user_id,
    token_hash,
    raw_token,
    expires_at,
    created_by
  )
  values (
    p_unit_id,
    v_owner,
    encode(extensions.digest(v_raw, 'sha256'), 'hex'),
    v_raw,
    v_expires,
    v_owner
  )
  returning id into v_id;

  return query select v_id, v_raw, v_expires;
end;
$function$;

comment on function public.create_application_link(uuid, integer) is
  'Mints the reusable public application link for a unit the caller owns (D-01/D-03a). Raw token is 32 bytes from extensions.gen_random_bytes, hex-encoded; token_hash is its SHA-256 and is the public lookup key. Refuses a unit the caller does not own and refuses while an unexpired unrevoked link already exists for that unit. Expiry defaults to 60 days (D-03) and is clamped to [1, 365].';

revoke all on function public.create_application_link(uuid, integer) from public;
grant execute on function public.create_application_link(uuid, integer) to authenticated;

-- =============================================================================
-- 2. revoke_application_link - stop accepting applications through one link.
--
--    Revoking affects only the link. Applications already received are never
--    touched, which is what the UI-SPEC section C confirm dialog promises the
--    owner in so many words.
-- =============================================================================
create or replace function public.revoke_application_link(p_link_id uuid)
  returns void
  language plpgsql
  security definer
  set search_path = public
as $function$
declare
  v_owner uuid := (select auth.uid());
  v_rows  integer;
begin
  if v_owner is null then
    raise exception 'not authenticated';
  end if;

  -- The ownership predicate lives in the WHERE clause, so a link belonging to
  -- another owner simply matches zero rows and falls into the same error as a
  -- link id that does not exist. One message for both, for the same
  -- non-enumeration reason as create_application_link.
  --
  -- `revoked_at is null` makes this idempotent-safe rather than idempotent: a
  -- second revoke raises rather than silently re-stamping a new revoked_at over
  -- the original, which would move the date shown in the UI expiry line.
  update public.rental_application_links
  set revoked_at = now()
  where id = p_link_id
    and owner_user_id = v_owner
    and revoked_at is null;

  get diagnostics v_rows = row_count;

  if v_rows = 0 then
    raise exception 'link not found';
  end if;
end;
$function$;

comment on function public.revoke_application_link(uuid) is
  'Stamps revoked_at on a link the caller owns. Applications already received through the link are untouched. Raises "link not found" for a missing link, another owner''s link, and an already-revoked link alike.';

revoke all on function public.revoke_application_link(uuid) from public;
grant execute on function public.revoke_application_link(uuid) to authenticated;
