-- Hotfix to phase_5_recognize_new_price_ids: that migration's first draft
-- accidentally also recreated `get_user_plan_limits(text)` (the 7-column
-- overload deliberately dropped in
-- 20260505230821_drop_legacy_get_user_plan_limits_text_overload.sql).
-- That overload triggers PostgREST PGRST203 ambiguity errors against the
-- uuid version, which broke tests/integration/rls/rpc-auth.test.ts.
--
-- The committed version of phase_5_recognize_new_price_ids.sql no longer
-- creates the text overload, but prod was applied with the older draft via
-- MCP, so this defensive drop is preserved for replay-from-zero correctness.
DROP FUNCTION IF EXISTS public.get_user_plan_limits(text);
