-- Cycle-1 followup for PR #677 (P1 security hardening).
--
-- ## P1-A — restore service_role EXECUTE on check_stripe_sync_status
--
-- The prior migration (20260507191140_p1_security_hardening.sql) ran
-- `revoke execute on function public.check_stripe_sync_status() from
-- public, authenticated`. The function was originally granted EXECUTE
-- only to `authenticated`; service_role had reachability via the
-- default `PUBLIC=X/postgres` grant Postgres assigns to every function.
-- Revoking from PUBLIC therefore removed service_role's path too —
-- contrary to the prior migration's comment which claimed
-- "service_role retains EXECUTE for admin observability".
--
-- This migration restores the explicit service_role grant so the
-- documentation matches reality. There's no immediate operational
-- impact because no Edge Function or app code calls this RPC via
-- service_role today (admin observability runs as the postgres
-- superuser via the SQL editor), but the implicit-grant ambiguity
-- is exactly the kind of drift that causes future breakage.
grant execute on function public.check_stripe_sync_status() to service_role;
