-- Drop the legacy `get_user_plan_limits(text)` overload — superseded by the
-- new uuid version introduced in 20260505213825_enforce_plan_limits.sql.
--
-- Cycle-2 review of #671 surfaced this: PostgREST cannot deterministically
-- pick between the text and uuid overloads when called with a UUID-as-string
-- arg, and raises PGRST203 "Could not choose the best candidate function".
-- This breaks tests/integration/rls/rpc-auth.test.ts:205-210, which calls
-- the function via `clientA.rpc(...)` to assert authenticated cross-user
-- access denial.
--
-- Same problem (and same fix) as 20251110151620_drop_duplicate_check_user_feature_access.sql.
--
-- Callers verified absent:
--   - src/                   — no calls
--   - supabase/functions/    — no calls (one comment reference in
--                              20260219100000_implement_check_user_feature_access.sql:29
--                              describing the algorithm, no actual invocation)
--   - tests/integration/     — only the rpc-auth.test.ts assertion above,
--                              which is updated in this PR to drop the
--                              now-meaningless check (the new uuid version
--                              is REVOKE'd from authenticated, so there's
--                              no IDOR surface to test).
--
-- The 7-column return shape (`property_limit, tenant_limit, unit_limit,
-- storage_gb, has_api_access, has_white_label, support_level`) is also
-- unused in the codebase — frontend reads `subscription_plan` directly
-- and resolves limits via TypeScript helpers or the DB triggers.

DROP FUNCTION IF EXISTS public.get_user_plan_limits(text);
