/**
 * Centralized constants for the frontend application
 */
export { QUERY_CACHE_TIMES } from './query-config'
export {
	PROPERTY_STATUS,
	LEASE_STATUS,
	UNIT_STATUS,
	MAINTENANCE_STATUS,
	MAINTENANCE_CATEGORY,
	TENANT_STATUS,
	PROPERTY_STATUS_LABELS,
	LEASE_STATUS_LABELS,
	UNIT_STATUS_LABELS,
	MAINTENANCE_STATUS_LABELS,
	MAINTENANCE_CATEGORY_LABELS,
	MAINTENANCE_CATEGORY_OPTIONS,
	TENANT_STATUS_LABELS
} from './status-values'
export { ERROR_MESSAGES } from './error-messages'
