/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./generated-schemas";
export type PublicInvitationType = z.infer<
  typeof generated.publicInvitationTypeSchema
>;
export type PublicSignatureMethod = z.infer<
  typeof generated.publicSignatureMethodSchema
>;
export type PublicStripeSubscriptionStatus = z.infer<
  typeof generated.publicStripeSubscriptionStatusSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicActivityRow = z.infer<
  typeof generated.publicActivityRowSchema
>;
export type PublicActivityInsert = z.infer<
  typeof generated.publicActivityInsertSchema
>;
export type PublicActivityUpdate = z.infer<
  typeof generated.publicActivityUpdateSchema
>;
export type PublicActivityRelationships = z.infer<
  typeof generated.publicActivityRelationshipsSchema
>;
export type PublicDocumentsRow = z.infer<
  typeof generated.publicDocumentsRowSchema
>;
export type PublicDocumentsInsert = z.infer<
  typeof generated.publicDocumentsInsertSchema
>;
export type PublicDocumentsUpdate = z.infer<
  typeof generated.publicDocumentsUpdateSchema
>;
export type PublicExpensesRow = z.infer<
  typeof generated.publicExpensesRowSchema
>;
export type PublicExpensesInsert = z.infer<
  typeof generated.publicExpensesInsertSchema
>;
export type PublicExpensesUpdate = z.infer<
  typeof generated.publicExpensesUpdateSchema
>;
export type PublicExpensesRelationships = z.infer<
  typeof generated.publicExpensesRelationshipsSchema
>;
export type PublicLeaseTenantsRow = z.infer<
  typeof generated.publicLeaseTenantsRowSchema
>;
export type PublicLeaseTenantsInsert = z.infer<
  typeof generated.publicLeaseTenantsInsertSchema
>;
export type PublicLeaseTenantsUpdate = z.infer<
  typeof generated.publicLeaseTenantsUpdateSchema
>;
export type PublicLeaseTenantsRelationships = z.infer<
  typeof generated.publicLeaseTenantsRelationshipsSchema
>;
export type PublicLeasesRow = z.infer<typeof generated.publicLeasesRowSchema>;
export type PublicLeasesInsert = z.infer<
  typeof generated.publicLeasesInsertSchema
>;
export type PublicLeasesUpdate = z.infer<
  typeof generated.publicLeasesUpdateSchema
>;
export type PublicLeasesRelationships = z.infer<
  typeof generated.publicLeasesRelationshipsSchema
>;
export type PublicMaintenanceRequestsRow = z.infer<
  typeof generated.publicMaintenanceRequestsRowSchema
>;
export type PublicMaintenanceRequestsInsert = z.infer<
  typeof generated.publicMaintenanceRequestsInsertSchema
>;
export type PublicMaintenanceRequestsUpdate = z.infer<
  typeof generated.publicMaintenanceRequestsUpdateSchema
>;
export type PublicMaintenanceRequestsRelationships = z.infer<
  typeof generated.publicMaintenanceRequestsRelationshipsSchema
>;
export type PublicNotificationLogsRow = z.infer<
  typeof generated.publicNotificationLogsRowSchema
>;
export type PublicNotificationLogsInsert = z.infer<
  typeof generated.publicNotificationLogsInsertSchema
>;
export type PublicNotificationLogsUpdate = z.infer<
  typeof generated.publicNotificationLogsUpdateSchema
>;
export type PublicNotificationLogsRelationships = z.infer<
  typeof generated.publicNotificationLogsRelationshipsSchema
>;
export type PublicNotificationsRow = z.infer<
  typeof generated.publicNotificationsRowSchema
>;
export type PublicNotificationsInsert = z.infer<
  typeof generated.publicNotificationsInsertSchema
>;
export type PublicNotificationsUpdate = z.infer<
  typeof generated.publicNotificationsUpdateSchema
>;
export type PublicNotificationsRelationships = z.infer<
  typeof generated.publicNotificationsRelationshipsSchema
>;
export type PublicPaymentMethodsRow = z.infer<
  typeof generated.publicPaymentMethodsRowSchema
>;
export type PublicPaymentMethodsInsert = z.infer<
  typeof generated.publicPaymentMethodsInsertSchema
>;
export type PublicPaymentMethodsUpdate = z.infer<
  typeof generated.publicPaymentMethodsUpdateSchema
>;
export type PublicPaymentMethodsRelationships = z.infer<
  typeof generated.publicPaymentMethodsRelationshipsSchema
>;
export type PublicPaymentSchedulesRow = z.infer<
  typeof generated.publicPaymentSchedulesRowSchema
>;
export type PublicPaymentSchedulesInsert = z.infer<
  typeof generated.publicPaymentSchedulesInsertSchema
>;
export type PublicPaymentSchedulesUpdate = z.infer<
  typeof generated.publicPaymentSchedulesUpdateSchema
>;
export type PublicPaymentSchedulesRelationships = z.infer<
  typeof generated.publicPaymentSchedulesRelationshipsSchema
>;
export type PublicPaymentTransactionsRow = z.infer<
  typeof generated.publicPaymentTransactionsRowSchema
>;
export type PublicPaymentTransactionsInsert = z.infer<
  typeof generated.publicPaymentTransactionsInsertSchema
>;
export type PublicPaymentTransactionsUpdate = z.infer<
  typeof generated.publicPaymentTransactionsUpdateSchema
>;
export type PublicPaymentTransactionsRelationships = z.infer<
  typeof generated.publicPaymentTransactionsRelationshipsSchema
>;
export type PublicProcessedInternalEventsRow = z.infer<
  typeof generated.publicProcessedInternalEventsRowSchema
>;
export type PublicProcessedInternalEventsInsert = z.infer<
  typeof generated.publicProcessedInternalEventsInsertSchema
>;
export type PublicProcessedInternalEventsUpdate = z.infer<
  typeof generated.publicProcessedInternalEventsUpdateSchema
>;
export type PublicPropertiesRow = z.infer<
  typeof generated.publicPropertiesRowSchema
>;
export type PublicPropertiesInsert = z.infer<
  typeof generated.publicPropertiesInsertSchema
>;
export type PublicPropertiesUpdate = z.infer<
  typeof generated.publicPropertiesUpdateSchema
>;
export type PublicPropertiesRelationships = z.infer<
  typeof generated.publicPropertiesRelationshipsSchema
>;
export type PublicPropertyImagesRow = z.infer<
  typeof generated.publicPropertyImagesRowSchema
>;
export type PublicPropertyImagesInsert = z.infer<
  typeof generated.publicPropertyImagesInsertSchema
>;
export type PublicPropertyImagesUpdate = z.infer<
  typeof generated.publicPropertyImagesUpdateSchema
>;
export type PublicPropertyImagesRelationships = z.infer<
  typeof generated.publicPropertyImagesRelationshipsSchema
>;
export type PublicPropertyOwnersRow = z.infer<
  typeof generated.publicPropertyOwnersRowSchema
>;
export type PublicPropertyOwnersInsert = z.infer<
  typeof generated.publicPropertyOwnersInsertSchema
>;
export type PublicPropertyOwnersUpdate = z.infer<
  typeof generated.publicPropertyOwnersUpdateSchema
>;
export type PublicPropertyOwnersRelationships = z.infer<
  typeof generated.publicPropertyOwnersRelationshipsSchema
>;
export type PublicRentDueRow = z.infer<typeof generated.publicRentDueRowSchema>;
export type PublicRentDueInsert = z.infer<
  typeof generated.publicRentDueInsertSchema
>;
export type PublicRentDueUpdate = z.infer<
  typeof generated.publicRentDueUpdateSchema
>;
export type PublicRentDueRelationships = z.infer<
  typeof generated.publicRentDueRelationshipsSchema
>;
export type PublicRentPaymentsRow = z.infer<
  typeof generated.publicRentPaymentsRowSchema
>;
export type PublicRentPaymentsInsert = z.infer<
  typeof generated.publicRentPaymentsInsertSchema
>;
export type PublicRentPaymentsUpdate = z.infer<
  typeof generated.publicRentPaymentsUpdateSchema
>;
export type PublicRentPaymentsRelationships = z.infer<
  typeof generated.publicRentPaymentsRelationshipsSchema
>;
export type PublicReportRunsRow = z.infer<
  typeof generated.publicReportRunsRowSchema
>;
export type PublicReportRunsInsert = z.infer<
  typeof generated.publicReportRunsInsertSchema
>;
export type PublicReportRunsUpdate = z.infer<
  typeof generated.publicReportRunsUpdateSchema
>;
export type PublicReportRunsRelationships = z.infer<
  typeof generated.publicReportRunsRelationshipsSchema
>;
export type PublicReportsRow = z.infer<typeof generated.publicReportsRowSchema>;
export type PublicReportsInsert = z.infer<
  typeof generated.publicReportsInsertSchema
>;
export type PublicReportsUpdate = z.infer<
  typeof generated.publicReportsUpdateSchema
>;
export type PublicReportsRelationships = z.infer<
  typeof generated.publicReportsRelationshipsSchema
>;
export type PublicSecurityAuditLogRow = z.infer<
  typeof generated.publicSecurityAuditLogRowSchema
>;
export type PublicSecurityAuditLogInsert = z.infer<
  typeof generated.publicSecurityAuditLogInsertSchema
>;
export type PublicSecurityAuditLogUpdate = z.infer<
  typeof generated.publicSecurityAuditLogUpdateSchema
>;
export type PublicSecurityAuditLogRelationships = z.infer<
  typeof generated.publicSecurityAuditLogRelationshipsSchema
>;
export type PublicSubscriptionsRow = z.infer<
  typeof generated.publicSubscriptionsRowSchema
>;
export type PublicSubscriptionsInsert = z.infer<
  typeof generated.publicSubscriptionsInsertSchema
>;
export type PublicSubscriptionsUpdate = z.infer<
  typeof generated.publicSubscriptionsUpdateSchema
>;
export type PublicSubscriptionsRelationships = z.infer<
  typeof generated.publicSubscriptionsRelationshipsSchema
>;
export type PublicTenantInvitationsRow = z.infer<
  typeof generated.publicTenantInvitationsRowSchema
>;
export type PublicTenantInvitationsInsert = z.infer<
  typeof generated.publicTenantInvitationsInsertSchema
>;
export type PublicTenantInvitationsUpdate = z.infer<
  typeof generated.publicTenantInvitationsUpdateSchema
>;
export type PublicTenantInvitationsRelationships = z.infer<
  typeof generated.publicTenantInvitationsRelationshipsSchema
>;
export type PublicTenantsRow = z.infer<typeof generated.publicTenantsRowSchema>;
export type PublicTenantsInsert = z.infer<
  typeof generated.publicTenantsInsertSchema
>;
export type PublicTenantsUpdate = z.infer<
  typeof generated.publicTenantsUpdateSchema
>;
export type PublicTenantsRelationships = z.infer<
  typeof generated.publicTenantsRelationshipsSchema
>;
export type PublicUnitsRow = z.infer<typeof generated.publicUnitsRowSchema>;
export type PublicUnitsInsert = z.infer<
  typeof generated.publicUnitsInsertSchema
>;
export type PublicUnitsUpdate = z.infer<
  typeof generated.publicUnitsUpdateSchema
>;
export type PublicUnitsRelationships = z.infer<
  typeof generated.publicUnitsRelationshipsSchema
>;
export type PublicUserAccessLogRow = z.infer<
  typeof generated.publicUserAccessLogRowSchema
>;
export type PublicUserAccessLogInsert = z.infer<
  typeof generated.publicUserAccessLogInsertSchema
>;
export type PublicUserAccessLogUpdate = z.infer<
  typeof generated.publicUserAccessLogUpdateSchema
>;
export type PublicUserAccessLogRelationships = z.infer<
  typeof generated.publicUserAccessLogRelationshipsSchema
>;
export type PublicUserFeatureAccessRow = z.infer<
  typeof generated.publicUserFeatureAccessRowSchema
>;
export type PublicUserFeatureAccessInsert = z.infer<
  typeof generated.publicUserFeatureAccessInsertSchema
>;
export type PublicUserFeatureAccessUpdate = z.infer<
  typeof generated.publicUserFeatureAccessUpdateSchema
>;
export type PublicUserFeatureAccessRelationships = z.infer<
  typeof generated.publicUserFeatureAccessRelationshipsSchema
>;
export type PublicUserPreferencesRow = z.infer<
  typeof generated.publicUserPreferencesRowSchema
>;
export type PublicUserPreferencesInsert = z.infer<
  typeof generated.publicUserPreferencesInsertSchema
>;
export type PublicUserPreferencesUpdate = z.infer<
  typeof generated.publicUserPreferencesUpdateSchema
>;
export type PublicUserPreferencesRelationships = z.infer<
  typeof generated.publicUserPreferencesRelationshipsSchema
>;
export type PublicUsersRow = z.infer<typeof generated.publicUsersRowSchema>;
export type PublicUsersInsert = z.infer<
  typeof generated.publicUsersInsertSchema
>;
export type PublicUsersUpdate = z.infer<
  typeof generated.publicUsersUpdateSchema
>;
export type PublicWebhookAttemptsRow = z.infer<
  typeof generated.publicWebhookAttemptsRowSchema
>;
export type PublicWebhookAttemptsInsert = z.infer<
  typeof generated.publicWebhookAttemptsInsertSchema
>;
export type PublicWebhookAttemptsUpdate = z.infer<
  typeof generated.publicWebhookAttemptsUpdateSchema
>;
export type PublicWebhookAttemptsRelationships = z.infer<
  typeof generated.publicWebhookAttemptsRelationshipsSchema
>;
export type PublicWebhookEventsRow = z.infer<
  typeof generated.publicWebhookEventsRowSchema
>;
export type PublicWebhookEventsInsert = z.infer<
  typeof generated.publicWebhookEventsInsertSchema
>;
export type PublicWebhookEventsUpdate = z.infer<
  typeof generated.publicWebhookEventsUpdateSchema
>;
export type PublicWebhookMetricsRow = z.infer<
  typeof generated.publicWebhookMetricsRowSchema
>;
export type PublicWebhookMetricsInsert = z.infer<
  typeof generated.publicWebhookMetricsInsertSchema
>;
export type PublicWebhookMetricsUpdate = z.infer<
  typeof generated.publicWebhookMetricsUpdateSchema
>;
export type PublicAcquireInternalEventLockArgs = z.infer<
  typeof generated.publicAcquireInternalEventLockArgsSchema
>;
export type PublicAcquireInternalEventLockReturns = z.infer<
  typeof generated.publicAcquireInternalEventLockReturnsSchema
>;
export type PublicAcquireWebhookEventLockWithIdArgs = z.infer<
  typeof generated.publicAcquireWebhookEventLockWithIdArgsSchema
>;
export type PublicAcquireWebhookEventLockWithIdReturns = z.infer<
  typeof generated.publicAcquireWebhookEventLockWithIdReturnsSchema
>;
export type PublicActivateLeaseWithPendingSubscriptionArgs = z.infer<
  typeof generated.publicActivateLeaseWithPendingSubscriptionArgsSchema
>;
export type PublicActivateLeaseWithPendingSubscriptionReturns = z.infer<
  typeof generated.publicActivateLeaseWithPendingSubscriptionReturnsSchema
>;
export type PublicCheckUserFeatureAccessArgs = z.infer<
  typeof generated.publicCheckUserFeatureAccessArgsSchema
>;
export type PublicCheckUserFeatureAccessReturns = z.infer<
  typeof generated.publicCheckUserFeatureAccessReturnsSchema
>;
export type PublicCleanupOldInternalEventsArgs = z.infer<
  typeof generated.publicCleanupOldInternalEventsArgsSchema
>;
export type PublicCleanupOldInternalEventsReturns = z.infer<
  typeof generated.publicCleanupOldInternalEventsReturnsSchema
>;
export type PublicCustomAccessTokenHookArgs = z.infer<
  typeof generated.publicCustomAccessTokenHookArgsSchema
>;
export type PublicCustomAccessTokenHookReturns = z.infer<
  typeof generated.publicCustomAccessTokenHookReturnsSchema
>;
export type PublicGetBillingInsightsArgs = z.infer<
  typeof generated.publicGetBillingInsightsArgsSchema
>;
export type PublicGetBillingInsightsReturns = z.infer<
  typeof generated.publicGetBillingInsightsReturnsSchema
>;
export type PublicGetCurrentPropertyOwnerIdArgs = z.infer<
  typeof generated.publicGetCurrentPropertyOwnerIdArgsSchema
>;
export type PublicGetCurrentPropertyOwnerIdReturns = z.infer<
  typeof generated.publicGetCurrentPropertyOwnerIdReturnsSchema
>;
export type PublicGetCurrentTenantIdArgs = z.infer<
  typeof generated.publicGetCurrentTenantIdArgsSchema
>;
export type PublicGetCurrentTenantIdReturns = z.infer<
  typeof generated.publicGetCurrentTenantIdReturnsSchema
>;
export type PublicGetCurrentUserTypeArgs = z.infer<
  typeof generated.publicGetCurrentUserTypeArgsSchema
>;
export type PublicGetCurrentUserTypeReturns = z.infer<
  typeof generated.publicGetCurrentUserTypeReturnsSchema
>;
export type PublicGetDashboardStatsArgs = z.infer<
  typeof generated.publicGetDashboardStatsArgsSchema
>;
export type PublicGetDashboardStatsReturns = z.infer<
  typeof generated.publicGetDashboardStatsReturnsSchema
>;
export type PublicGetDashboardTimeSeriesArgs = z.infer<
  typeof generated.publicGetDashboardTimeSeriesArgsSchema
>;
export type PublicGetDashboardTimeSeriesReturns = z.infer<
  typeof generated.publicGetDashboardTimeSeriesReturnsSchema
>;
export type PublicGetMaintenanceAnalyticsArgs = z.infer<
  typeof generated.publicGetMaintenanceAnalyticsArgsSchema
>;
export type PublicGetMaintenanceAnalyticsReturns = z.infer<
  typeof generated.publicGetMaintenanceAnalyticsReturnsSchema
>;
export type PublicGetMetricTrendArgs = z.infer<
  typeof generated.publicGetMetricTrendArgsSchema
>;
export type PublicGetMetricTrendReturns = z.infer<
  typeof generated.publicGetMetricTrendReturnsSchema
>;
export type PublicGetOccupancyTrendsOptimizedArgs = z.infer<
  typeof generated.publicGetOccupancyTrendsOptimizedArgsSchema
>;
export type PublicGetOccupancyTrendsOptimizedReturns = z.infer<
  typeof generated.publicGetOccupancyTrendsOptimizedReturnsSchema
>;
export type PublicGetOwnerLeaseTenantIdsArgs = z.infer<
  typeof generated.publicGetOwnerLeaseTenantIdsArgsSchema
>;
export type PublicGetOwnerLeaseTenantIdsReturns = z.infer<
  typeof generated.publicGetOwnerLeaseTenantIdsReturnsSchema
>;
export type PublicGetPropertyPerformanceCachedArgs = z.infer<
  typeof generated.publicGetPropertyPerformanceCachedArgsSchema
>;
export type PublicGetPropertyPerformanceCachedReturns = z.infer<
  typeof generated.publicGetPropertyPerformanceCachedReturnsSchema
>;
export type PublicGetPropertyPerformanceTrendsArgs = z.infer<
  typeof generated.publicGetPropertyPerformanceTrendsArgsSchema
>;
export type PublicGetPropertyPerformanceTrendsReturns = z.infer<
  typeof generated.publicGetPropertyPerformanceTrendsReturnsSchema
>;
export type PublicGetRevenueTrendsOptimizedArgs = z.infer<
  typeof generated.publicGetRevenueTrendsOptimizedArgsSchema
>;
export type PublicGetRevenueTrendsOptimizedReturns = z.infer<
  typeof generated.publicGetRevenueTrendsOptimizedReturnsSchema
>;
export type PublicGetTenantLeaseIdsArgs = z.infer<
  typeof generated.publicGetTenantLeaseIdsArgsSchema
>;
export type PublicGetTenantLeaseIdsReturns = z.infer<
  typeof generated.publicGetTenantLeaseIdsReturnsSchema
>;
export type PublicGetTenantPropertyIdsArgs = z.infer<
  typeof generated.publicGetTenantPropertyIdsArgsSchema
>;
export type PublicGetTenantPropertyIdsReturns = z.infer<
  typeof generated.publicGetTenantPropertyIdsReturnsSchema
>;
export type PublicGetTenantUnitIdsArgs = z.infer<
  typeof generated.publicGetTenantUnitIdsArgsSchema
>;
export type PublicGetTenantUnitIdsReturns = z.infer<
  typeof generated.publicGetTenantUnitIdsReturnsSchema
>;
export type PublicGetTenantsByOwnerArgs = z.infer<
  typeof generated.publicGetTenantsByOwnerArgsSchema
>;
export type PublicGetTenantsByOwnerReturns = z.infer<
  typeof generated.publicGetTenantsByOwnerReturnsSchema
>;
export type PublicGetTenantsWithLeaseByOwnerArgs = z.infer<
  typeof generated.publicGetTenantsWithLeaseByOwnerArgsSchema
>;
export type PublicGetTenantsWithLeaseByOwnerReturns = z.infer<
  typeof generated.publicGetTenantsWithLeaseByOwnerReturnsSchema
>;
export type PublicGetUserDashboardActivitiesArgs = z.infer<
  typeof generated.publicGetUserDashboardActivitiesArgsSchema
>;
export type PublicGetUserDashboardActivitiesReturns = z.infer<
  typeof generated.publicGetUserDashboardActivitiesReturnsSchema
>;
export type PublicGetUserPlanLimitsArgs = z.infer<
  typeof generated.publicGetUserPlanLimitsArgsSchema
>;
export type PublicGetUserPlanLimitsReturns = z.infer<
  typeof generated.publicGetUserPlanLimitsReturnsSchema
>;
export type PublicHealthCheckArgs = z.infer<
  typeof generated.publicHealthCheckArgsSchema
>;
export type PublicHealthCheckReturns = z.infer<
  typeof generated.publicHealthCheckReturnsSchema
>;
export type PublicParseAddressArgs = z.infer<
  typeof generated.publicParseAddressArgsSchema
>;
export type PublicParseAddressReturns = z.infer<
  typeof generated.publicParseAddressReturnsSchema
>;
export type PublicRecordProcessedStripeEventLockArgs = z.infer<
  typeof generated.publicRecordProcessedStripeEventLockArgsSchema
>;
export type PublicRecordProcessedStripeEventLockReturns = z.infer<
  typeof generated.publicRecordProcessedStripeEventLockReturnsSchema
>;
export type PublicSignLeaseAndCheckActivationArgs = z.infer<
  typeof generated.publicSignLeaseAndCheckActivationArgsSchema
>;
export type PublicSignLeaseAndCheckActivationReturns = z.infer<
  typeof generated.publicSignLeaseAndCheckActivationReturnsSchema
>;
export type PublicUserIsTenantArgs = z.infer<
  typeof generated.publicUserIsTenantArgsSchema
>;
export type PublicUserIsTenantReturns = z.infer<
  typeof generated.publicUserIsTenantReturnsSchema
>;
export type PublicStdaddr = z.infer<typeof generated.publicStdaddrSchema>;
