name: Claude PR Review

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-review:
    # Only run when PR is opened/synchronized, or when a comment mentions @claude
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git diff
          
      - name: Run Claude Code Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mode: agent
          direct_prompt: |
            Review this pull request for:
            - TypeScript type safety issues
            - Security vulnerabilities
            - Performance problems
            - Code quality and best practices
            - Potential bugs
            
            Focus on the changed files only. Provide specific, actionable feedback.
            Format your response as a GitHub comment with markdown.
          timeout_minutes: 10