name: Post-Deploy Monitoring

on:
  workflow_run:
    workflows: ['CI/CD']
    branches: [main]
    types:
      - completed
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  production-health:
    name: Production Healthcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Hit API health endpoint
        run: |
          for i in {1..3}; do
            if curl -fsSL https://api.tenantflow.app/health >/dev/null; then
              echo "API healthy"
              exit 0
            fi
            sleep 5
          done
          echo "API health endpoint failed"
          exit 1

      - name: Hit frontend availability
        run: |
          if ! curl -fsSL https://tenantflow.app >/dev/null; then
            echo "Frontend check failed"
            exit 1
          fi

  staging-preview:
    name: Staging snapshot
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: always()
    steps:
      - name: Staging API check
        run: curl -fsSL https://staging-api.tenantflow.app/health >/dev/null

      - name: Staging frontend check
        run: curl -fsSL https://staging.tenantflow.app >/dev/null
