name: PR

on:
  pull_request:
    branches: [main, develop]

jobs:
  check:
    name: PR Check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Quick Check
        run: |
          echo "PR check passed"