name: PR

on:
  pull_request:
    branches: [main, develop]

jobs:
  check:
    name: PR Check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Quick Check
        run: |
          echo "🔧 Installing dependencies..."
          npm ci --prefer-offline --no-audit --fund=false
          echo "✅ Dependencies installed"
          
          echo "🔧 Running lint check..."
          npm run lint
          echo "✅ Lint check passed"
          
          echo "🔧 Building shared package..."
          npx turbo build --filter=@tenantflow/shared
          echo "✅ Shared package built"
          
          echo "✅ PR check completed successfully"