name: Simple PR Check

on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: PR Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --fund=false
        
      - name: Run lint check
        run: npm run lint
        continue-on-error: true
        
      - name: Run type check  
        run: npm run typecheck
        continue-on-error: true
        
      - name: Build packages
        run: npm run build
        continue-on-error: true
        
      - name: ✅ Basic checks complete
        run: |
          echo "PR basic validation complete"
          echo "Note: Some checks may have warnings but PR is not blocked"