name: playwright-smoke

on:
  workflow_call:
    inputs:
      node-version:
        default: '20'
        type: string
      pnpm-version:
        default: '10.18.2'
        type: string
      dev-server-command:
        description: Command that starts the app for smoke tests
        type: string
        default: pnpm --filter @repo/frontend dev -- -p 3940
      dev-server-timeout-seconds:
        default: 90
        type: number
      playwright-grep:
        description: Playwright grep expression for smoke tests
        type: string
        default: '@smoke'
      base-url:
        description: Base URL for Playwright
        type: string
        default: http://localhost:3940
      extra-args:
        description: Additional args for Playwright
        required: false
        default: ''
        type: string

permissions:
  contents: read

env:
  CI: true
  PLAYWRIGHT_BROWSERS_PATH: 0

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps

      - name: Start dev server
        id: devserver
        run: |
          (${{ inputs.dev-server-command }} > dev-server.log 2>&1) &
          FRONTEND_PID=$!
          echo "pid=$FRONTEND_PID" >> $GITHUB_OUTPUT

      - name: Wait for server to be ready
        run: |
          for i in $(seq 1 ${{ inputs.dev-server-timeout-seconds }}); do
            if curl -sSf "${{ inputs.base-url }}" >/dev/null 2>&1; then
              echo "Server is ready"
              exit 0
            fi
            sleep 1
          done
          echo "Server did not start in time" >&2
          exit 1

      - name: Run Playwright smoke tests
        env:
          PLAYWRIGHT_BASE_URL: ${{ inputs.base-url }}
        run: |
          pnpm exec playwright test --grep "${{ inputs.playwright-grep }}" --reporter=list ${{ inputs.extra-args }}

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-smoke-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Stop dev server
        if: always()
        run: |
          if [ -n "${{ steps.devserver.outputs.pid }}" ]; then
            kill ${{ steps.devserver.outputs.pid }} || true
          fi

      - name: Upload dev server log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dev-server-log
          path: dev-server.log
          if-no-files-found: ignore
