name: Storybook CI - Build, Test, and Visual Testing

on:
  push:
    branches: [ main, develop, 'feat/*' ]
  pull_request:
    branches: [ main, develop ]

# Cancel previous workflow runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Enable Node.js performance optimizations
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # Cache key for dependencies
      cache-key: ${{ steps.cache-keys.outputs.cache-key }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate cache keys
        id: cache-keys
        run: |
          echo "cache-key=${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
        
      - name: Generate Prisma client
        run: npm run db:generate --if-present
        
      - name: Build shared packages
        run: npm run build --filter=@repo/shared --if-present
        
      - name: Build Storybook
        run: |
          cd apps/storybook
          npm run build-storybook
          
      - name: Cache Storybook build
        uses: actions/cache@v4
        with:
          path: apps/storybook/storybook-static
          key: storybook-build-${{ github.sha }}
          
      - name: Upload Storybook build artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: apps/storybook/storybook-static/
          retention-days: 7

  test:
    needs: [setup, build]
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        test-type: [interaction, accessibility, performance]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        
      - name: Download Storybook build
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: apps/storybook/storybook-static/
          
      - name: Start Storybook server
        run: |
          cd apps/storybook
          npx http-server storybook-static -p 6006 -s &
          sleep 10
          
      - name: Run interaction tests
        if: matrix.test-type == 'interaction'
        run: |
          cd apps/storybook
          npm run test-storybook:ci
          
      - name: Run accessibility tests
        if: matrix.test-type == 'accessibility'
        run: |
          cd apps/storybook
          npm run test:a11y
          
      - name: Run performance tests
        if: matrix.test-type == 'performance'
        run: |
          cd apps/storybook
          npm run test:perf
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-type }}
          path: |
            apps/storybook/test-results/
            apps/storybook/coverage/
          retention-days: 7

  visual-testing:
    needs: [setup, build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Chromatic needs full git history for TurboSnap
          fetch-depth: 0
          
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
        
      - name: Download Storybook build
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: apps/storybook/storybook-static/
          
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: apps/storybook/storybook-static
          # Skip Chromatic on dependabot PRs
          skip: 'dependabot/**'
          # Auto accept changes on main branch
          autoAcceptChanges: main
          # Exit with code 0 to not fail CI on visual changes
          exitZeroOnChanges: true
          # Enable TurboSnap for faster builds
          onlyChanged: true
          # Optimize upload
          zip: true
          # Trace changed files
          traceChanged: expanded
          # Ignore specific paths
          untraced: |
            node_modules/**
            .turbo/**
            coverage/**
            
      - name: Comment on PR with Chromatic link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `## 🎨 Visual Testing Results
            
            **Storybook**: [View Stories](https://689cf99e73396c4c66b53bd0-vvpdmvflew.chromatic.com/)
            **Chromatic**: [Review Changes](https://www.chromatic.com/builds?appId=689cf99e73396c4c66b53bd0)
            
            Visual regression testing completed successfully!
            
            ### What was tested:
            - 🧩 **14 components** with **81 stories**
            - 🎯 **Component interactions** and state changes
            - ♿ **Accessibility compliance** (WCAG 2.1 AA)
            - 📊 **Performance monitoring** and budgets
            - 🎨 **Visual consistency** across breakpoints
            
            If there are visual changes, review them in Chromatic before merging.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

  deploy-storybook:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [build, test, visual-testing]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download Storybook build
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: apps/storybook/storybook-static/
          
      - name: Deploy Storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/storybook/storybook-static
          destination_dir: storybook
          
      - name: Create deployment summary
        run: |
          echo "## 🚀 Storybook Deployment" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Storybook URL**: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/storybook/" >> $GITHUB_STEP_SUMMARY
          echo "**Chromatic URL**: https://689cf99e73396c4c66b53bd0-vvpdmvflew.chromatic.com/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Features Deployed:" >> $GITHUB_STEP_SUMMARY
          echo "- 🧩 Interactive component library" >> $GITHUB_STEP_SUMMARY
          echo "- 🎨 Complete design system documentation" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 Performance monitoring tools" >> $GITHUB_STEP_SUMMARY
          echo "- ♿ Accessibility testing integration" >> $GITHUB_STEP_SUMMARY
          echo "- 🔄 Component consolidation examples" >> $GITHUB_STEP_SUMMARY