name: tests

on:
  workflow_call:
    inputs:
      node-version:
        default: '22'
        type: string
      pnpm-version:
        default: '10.18.3'
        type: string
      test-script:
        description: Command to execute tests
        default: pnpm test
        type: string

permissions:
  contents: read

env:
  CI: true

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup Turbo Cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run tests
        run: ${{ inputs.test-script }}
