jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '24'
      
      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit --omit=optional
        
      - name: Install turbo globally for CI
        run: npm install -g turbo@2.5.6
        
      - name: Build with global turbo
        run: turbo build
        env:
          NEXT_PUBLIC_API_URL: https://test-api.example.com
          NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_123
          NEXT_PUBLIC_POSTHOG_KEY: test-posthog
          NEXT_PUBLIC_POSTHOG_HOST: https://app.posthog.com
          NEXT_PUBLIC_APP_URL: https://test-app.example.com
name: Test
on:
  - push
